-- Удаление таблиц в порядке обратном созданию (сначала дочерние, затем родительские)
DROP TABLE IF EXISTS FORWARD_MESSAGE;
DROP TABLE IF EXISTS REACTION;
DROP TABLE IF EXISTS ATTACHMENT;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CHAT_MEMBER;
DROP TABLE IF EXISTS CHAT;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS COMMUNITY_SUBSCRIBER;
DROP TABLE IF EXISTS COMMUNITY_AUTHOR;
DROP TABLE IF EXISTS COMMUNITY;
DROP TABLE IF EXISTS FRIEND_RELATIONSHIP;
DROP TABLE IF EXISTS PROFILE;

-- Удаление пользовательских типов (ENUM)
DROP TYPE IF EXISTS reaction_type_enum;
DROP TYPE IF EXISTS reaction_obj_type_enum;
DROP TYPE IF EXISTS attachment_obj_type_enum;
DROP TYPE IF EXISTS comment_obj_type_enum;
DROP TYPE IF EXISTS role_enum;
DROP TYPE IF EXISTS community_status_enum;
DROP TYPE IF EXISTS friendship_status_enum;