CREATE TYPE friendship_status_enum AS ENUM ('pending', 'accepted', 'rejected', 'blocked');
CREATE TYPE role_enum AS ENUM ('admin', 'moderator', 'member', 'owner');
CREATE TYPE attachment_obj_type_enum AS ENUM ('message', 'comment', 'profile', 'community');
CREATE TYPE application_category_enum AS ENUM (
    'app_freezing', -- Приложение зависает/тормозит
    'page_not_loading', -- Не загружается страница
    'chat_not_working',
    'profile_not_working',
    'messenger_not_working',
    'friend_not_working',
    'auth_problem'-- Проблема с авторизацией/входом
    );

CREATE TYPE application_status_enum AS ENUM ('open','inWork','closed');


CREATE TABLE users
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      TEXT UNIQUE,
    phone      TEXT UNIQUE,
    role       role_enum          default 'member',
    password   TEXT      NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT email_or_phone_required CHECK (email IS NOT NULL OR phone IS NOT NULL),
    CONSTRAINT password_length CHECK (LENGTH(password) >= 8),
    CONSTRAINT email_length CHECK (LENGTH(email) <= 254),
    CONSTRAINT phone_length CHECK (LENGTH(phone) <= 20)
);

CREATE TABLE profiles
(
    user_id      INT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    first_name   TEXT      NOT NULL CHECK (LENGTH(first_name) BETWEEN 1 AND 64),
    last_name    TEXT      NOT NULL CHECK (LENGTH(last_name) BETWEEN 1 AND 64),
    avatar_path  TEXT,
    header_path  TEXT,
    about_myself TEXT CHECK (LENGTH(about_myself) <= 256),
    gender       TEXT      NOT NULL,
    dob          TIMESTAMP NOT NULL,

    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT avatar_length CHECK (LENGTH(avatar_path) <= 512),
    CONSTRAINT header_length CHECK (LENGTH(header_path) <= 512)
);


CREATE TABLE friend_relationships
(
    first_user_id  INT                    NOT NULL,
    second_user_id INT                    NOT NULL,
    action_user_id INT                    NOT NULL, --кто отправил запрос
    status         friendship_status_enum NOT NULL DEFAULT 'pending',
    created_at     TIMESTAMP              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP              NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (first_user_id, second_user_id),
    FOREIGN KEY (first_user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (second_user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (action_user_id) REFERENCES users (id) ON DELETE CASCADE,

    -- Ограничения
    CONSTRAINT no_self_friendship CHECK (first_user_id != second_user_id),
    CONSTRAINT ordered_friendship CHECK (first_user_id < second_user_id),
    CONSTRAINT action_user_in_relationship CHECK (action_user_id IN (first_user_id, second_user_id))
);

CREATE TABLE chats
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT               DEFAULT NULL,
    is_group   BOOLEAN            DEFAULT FALSE,
    CONSTRAINT name_length CHECK (LENGTH(name) BETWEEN 5 AND 64),
    avatar     TEXT               DEFAULT NULL,
    CONSTRAINT avatar_length CHECK (LENGTH(avatar) <= 512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_members
(
    chat_id              INT       NOT NULL,
    member_id            INT       NOT NULL,
    role                 role_enum NOT NULL DEFAULT 'member',
    last_read_message_id INT                DEFAULT 0,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chat_id, member_id),
    FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ТАБЛИЦА ДЛЯ СТИКЕРПАКОВ
CREATE TABLE sticker_packs (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT      NOT NULL,
    cover_path  TEXT      NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT name_length CHECK (LENGTH(name) BETWEEN 1 AND 64),
    CONSTRAINT cover_path_length CHECK (LENGTH(cover_path) BETWEEN 1 AND 512)
);

-- ТАБЛИЦА ДЛЯ СТИКЕРОВ
CREATE TABLE stickers (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id         INT       NOT NULL REFERENCES sticker_packs(id) ON DELETE CASCADE,
    file_path       TEXT      NOT NULL,
    position        INT       NOT NULL DEFAULT 0,  -- порядковый номер в пачке
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT file_path_length CHECK (LENGTH(file_path) BETWEEN 1 AND 512),
    CONSTRAINT position_non_negative CHECK (position >= 0)
);

-- ТАБЛИЦА ДЛЯ ВЛОЖЕНИЙ СООБЩЕНИЙ, КОММЕНТАРИЕВ, ПРОФИЛЕЙ, СООБЩЕСТВ
CREATE TABLE attachments
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_id     INT                      NOT NULL,
    obj_type   attachment_obj_type_enum NOT NULL,
    file_path  TEXT                     NOT NULL,
    CONSTRAINT file_path_length CHECK (LENGTH(file_path) BETWEEN 1 AND 512),
    created_at TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id           INT       NOT NULL,
    chat_id             INT       NOT NULL,
    replayed_message_id INT,
    text                TEXT      NOT NULL,
    sticker_id          INT REFERENCES stickers(id) ON DELETE SET NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id),
    FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE
);

-- ТАБЛИЦА СООБЩЕСТВ
CREATE TABLE communities (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    description     TEXT NOT NULL,
    creator_id      INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    avatar_path     TEXT,
    cover_path      TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT name_length          CHECK (LENGTH(name) BETWEEN 3 AND 48),
    CONSTRAINT description_length   CHECK (LENGTH(description) BETWEEN 0 AND 512)
);

-- ПОДПИСКИ НА СООБЩЕСТВА
CREATE TABLE community_subscriptions (
    community_id    INT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    user_id         INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (community_id, user_id)
);

CREATE TABLE posts
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id       INT       NOT NULL,
    community_id    INT REFERENCES communities(id) ON DELETE CASCADE,
    text            TEXT      NOT NULL,
    CONSTRAINT      text_length CHECK (LENGTH(text) BETWEEN 0 AND 4096),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ТАБЛИЦА ДЛЯ ЛАЙКОВ ПОСТОВ
CREATE TABLE post_likes
(
    post_id    INT       NOT NULL,
    user_id    INT       NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, user_id),
    FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ТАБЛИЦА ДЛЯ ВЛОЖЕНИЙ ПОСТОВ
CREATE TABLE post_attachments
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    INT       NOT NULL,
    file_path  TEXT      NOT NULL,
    CONSTRAINT file_path_length CHECK (LENGTH(file_path) BETWEEN 1 AND 512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);

-- ТАБЛИЦА ДЛЯ ФОТОГРАФИЙ ПОСТОВ
CREATE TABLE post_photos
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    INT       NOT NULL,
    file_path  TEXT      NOT NULL,
    CONSTRAINT file_path_length CHECK (LENGTH(file_path) BETWEEN 1 AND 512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE TABLE applications
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id       INT                                DEFAULT NULL,
    temp_session_id UUID                               DEFAULT NULL,
    text            TEXT                      NOT NULL,
    category        application_category_enum NOT NULL,
    status          application_status_enum            DEFAULT 'open',
    created_at      TIMESTAMP                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_req       TEXT                      NOT NULL,
    email_feedback  TEXT                      NOT NULL,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

--ТАБЛИЦА ДЛЯ КОММЕНТАРИЕВ ПОСТОВ 
CREATE TABLE comments
(
    id              INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         INT     NOT NULL    REFERENCES posts(id) ON DELETE CASCADE,
    author_id       INT     NOT NULL    REFERENCES users(id) ON DELETE CASCADE,
    parent_id       INT                 REFERENCES comments(id) ON DELETE CASCADE,
    text            TEXT    NOT NULL,
    CONSTRAINT text_length CHECK (LENGTH(text) BETWEEN 1 AND 4096),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_parent_id ON comments(parent_id);

CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;

$$ LANGUAGE plpgsql;
DO
$$
    DECLARE
        r           RECORD;
        trig_exists INT;
    BEGIN
        FOR r IN
            SELECT table_schema, table_name
            FROM information_schema.columns
            WHERE column_name = 'updated_at'
              AND table_schema = 'public'
            LOOP
                SELECT COUNT(*)
                INTO trig_exists
                FROM pg_trigger
                WHERE tgname = 'set_updated_at'
                  AND tgrelid = (r.table_schema || '.' || r.table_name)::regclass;

                IF trig_exists = 0 THEN
                    EXECUTE format('
                CREATE TRIGGER set_updated_at
                BEFORE UPDATE ON %I.%I
                FOR EACH ROW
                EXECUTE FUNCTION update_timestamp();
            ', r.table_schema, r.table_name);
                END IF;
            END LOOP;
    END
$$;

-- Добавляем стикерпак
DO $$
DECLARE
    memes_pack_id INTEGER;
BEGIN
    -- Добавляем стикерпак
    INSERT INTO sticker_packs (name, cover_path) 
    VALUES ('Funny Memes', '/uploads/stickers/memes/meme1.jpg')
    RETURNING id INTO memes_pack_id;
    
    -- Добавляем стикеры
    INSERT INTO stickers (pack_id, file_path, position) VALUES
    (memes_pack_id, '/uploads/stickers/memes/meme1.jpg', 1),
    (memes_pack_id, '/uploads/stickers/memes/meme2.jpg', 2),
    (memes_pack_id, '/uploads/stickers/memes/meme3.jpg', 3),
    (memes_pack_id, '/uploads/stickers/memes/meme4.jpg', 4);
END $$;
