version: "2"
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - govt
    - staticcheck
    - bodyclose
    - contextcheck
    - errcheck
    - asciicheck
    - copyloopvar
    - decorder
    - goconst
    - prealloc
    - unparam
    - unused
    - unconvert
    - gocritic
    - gocyclo
    - ineffassign
    - nakedret
    - errorlint
    - err113
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
