FROM elastic/elasticsearch:8.14.0

# Устанавливаем ICU plugin
RUN elasticsearch-plugin install --batch analysis-icu
RUN elasticsearch-plugin install analysis-phonetic
COPY /elastic/synonyms_community.txt /usr/share/elasticsearch/config/elastic/synonyms_community.txt
COPY /elastic/synonyms_profile.txt /usr/share/elasticsearch/config/elastic/synonyms_profile.txt
