services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    image: ${MIGRATIONS_IMAGE:-local/migrations:latest}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - network
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: main
    image: ${MAIN_IMAGE:-local/main:latest}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - network
    command: ./main
    volumes:
      - shared_uploads:/app/uploads
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth
    image: ${AUTH_IMAGE:-local/auth:latest}
    env_file:
      - .env
    ports:
      - "50051:8080"
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - network
    command: ./main
    volumes:
      - shared_uploads:/app/uploads
  profile:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: profile
    image: ${PROFILE_IMAGE:-local/profile:latest}
    env_file:
      - .env
    ports:
      - "50052:8080"
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - network
    command: ./main
    volumes:
      - shared_uploads:/app/uploads

  friend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: friend
    image: ${FRIEND_IMAGE:-local/friend:latest}
    env_file:
      - .env
    ports:
      - "50053:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      auth:
        condition: service_started
      profile:
        condition: service_started
    networks:
      - network
    command: ./main
    volumes:
      - shared_uploads:/app/uploads

  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: ${PG_IMAGE:-local/pg:latest}
    container_name: vk_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pglogs:/var/lib/postgresql/log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - network

  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0 --port 6380 --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6380"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6380 -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network

  elasticsearch:
    image: ${ELASTIC_IMAGE:-local/elasticsearch:latest}
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_USERNAME=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - logger.level=ERROR
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s --user ${ELASTIC_USER}:${ELASTIC_PASSWORD} http://elasticsearch:9200/ | grep -q 'You Know, for Search'"]
      interval: 10s
      timeout: 10s
      retries: 20
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - network

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--log.level=error'
    networks:
      - network
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8089:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    devices:
      - /dev/kmsg
    privileged: true
    command:
      - "--docker_only"
      - "--logtostderr"
      - "--stderrthreshold=1"
    networks:
      - network
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--log.level=error'
    networks:
      - network
    depends_on:
      - node-exporter
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8020:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=error
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - network
    depends_on:
      - prometheus


  nginx:
    image: ${NGINX_IMAGE:-local/nginx:latest}
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./certbot-webroot:/var/www/certbot
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - main
    restart: unless-stopped
    networks:
      - network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email mr.loshkariov@yandex.ru --agree-tos --no-eff-email --force-renewal
      -d unitesm.ru
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot

  certbot-renew:
    image: certbot/certbot:latest
    container_name: certbot-renew
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: >
      sh -c "while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h;
      done"
    restart: unless-stopped

  volume-init:
    image: ${VOLUME_IMAGE:-local/volume:latest}
    build:
      context: .
      dockerfile: Dockerfile.volume
    volumes:
      - shared_uploads:/shared




networks:
  network:
    driver: bridge

volumes:
  pg_data:
  es_data:
  shared_uploads:
  prometheus_data:
  grafana_data:
