server {
    # Для локалки — HTTP, для продакшена можно слушать 80 и редиректить
    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/nginx/certs/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;


    server_name localhost unitesm.ru;

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Основные прокси-блоки — пишем один раз, будут работать и для HTTP, и для HTTPS
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://main:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
