-- Создание ролей для 4 микросервисов
CREATE ROLE ${MAIN_DB_USER}
    WITH LOGIN
    PASSWORD '${MAIN_DB_PASSWORD}'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

CREATE ROLE ${AUTH_DB_USER}
    WITH LOGIN
    PASSWORD '${AUTH_DB_PASSWORD}'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

CREATE ROLE ${PROFILE_DB_USER}
    WITH LOGIN
    PASSWORD '${PROFILE_DB_PASSWORD}'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

CREATE ROLE ${FRIEND_DB_USER}
    WITH LOGIN
    PASSWORD '${FRIEND_DB_PASSWORD}'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

GRANT CONNECT ON DATABASE ${DB_NAME} TO ${MAIN_DB_USER};
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${AUTH_DB_USER};
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${PROFILE_DB_USER};
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${FRIEND_DB_USER};

GRANT USAGE ON SCHEMA public TO ${MAIN_DB_USER};
GRANT USAGE ON SCHEMA public TO ${AUTH_DB_USER};
GRANT USAGE ON SCHEMA public TO ${PROFILE_DB_USER};
GRANT USAGE ON SCHEMA public TO ${FRIEND_DB_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE chats, chat_members, sticker_packs, stickers, attachments, messages, communities, community_subscriptions, posts, post_likes, post_attachments, post_photos, applications, comments TO ${MAIN_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO ${AUTH_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE profiles TO ${PROFILE_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE friend_relationships TO ${FRIEND_DB_USER};


