// Code generated by MockGen. DO NOT EDIT.
// Source: domain/session.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockSessionStore) AddSession(ctx context.Context, userID int32) (*domain.SIDAndSCRFToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", ctx, userID)
	ret0, _ := ret[0].(*domain.SIDAndSCRFToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSession indicates an expected call of AddSession.
func (mr *MockSessionStoreMockRecorder) AddSession(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockSessionStore)(nil).AddSession), ctx, userID)
}

// DeleteSession mocks base method.
func (m *MockSessionStore) DeleteSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionStoreMockRecorder) DeleteSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionStore)(nil).DeleteSession), ctx, sessionID)
}

// GetSessionBySessionID mocks base method.
func (m *MockSessionStore) GetSessionBySessionID(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionBySessionID indicates an expected call of GetSessionBySessionID.
func (mr *MockSessionStoreMockRecorder) GetSessionBySessionID(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionBySessionID", reflect.TypeOf((*MockSessionStore)(nil).GetSessionBySessionID), ctx, sessionID)
}
