// Code generated by MockGen. DO NOT EDIT.
// Source: domain/message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageStore is a mock of MessageStore interface.
type MockMessageStore struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStoreMockRecorder
}

// MockMessageStoreMockRecorder is the mock recorder for MockMessageStore.
type MockMessageStoreMockRecorder struct {
	mock *MockMessageStore
}

// NewMockMessageStore creates a new mock instance.
func NewMockMessageStore(ctrl *gomock.Controller) *MockMessageStore {
	mock := &MockMessageStore{ctrl: ctrl}
	mock.recorder = &MockMessageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStore) EXPECT() *MockMessageStoreMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockMessageStore) CreateMessage(ctx context.Context, message domain.Message) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, message)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockMessageStoreMockRecorder) CreateMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockMessageStore)(nil).CreateMessage), ctx, message)
}

// GetMessageAttachments mocks base method.
func (m *MockMessageStore) GetMessageAttachments(ctx context.Context, messageID int32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageAttachments", ctx, messageID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageAttachments indicates an expected call of GetMessageAttachments.
func (mr *MockMessageStoreMockRecorder) GetMessageAttachments(ctx, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageAttachments", reflect.TypeOf((*MockMessageStore)(nil).GetMessageAttachments), ctx, messageID)
}

// GetMessagesByChatId mocks base method.
func (m *MockMessageStore) GetMessagesByChatId(ctx context.Context, chatID, limit, offset int32) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByChatId", ctx, chatID, limit, offset)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByChatId indicates an expected call of GetMessagesByChatId.
func (mr *MockMessageStoreMockRecorder) GetMessagesByChatId(ctx, chatID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByChatId", reflect.TypeOf((*MockMessageStore)(nil).GetMessagesByChatId), ctx, chatID, limit, offset)
}

// GetStickerPath mocks base method.
func (m *MockMessageStore) GetStickerPath(ctx context.Context, stickerID int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerPath", ctx, stickerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerPath indicates an expected call of GetStickerPath.
func (mr *MockMessageStoreMockRecorder) GetStickerPath(ctx, stickerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerPath", reflect.TypeOf((*MockMessageStore)(nil).GetStickerPath), ctx, stickerID)
}

// SaveMessageAttachments mocks base method.
func (m *MockMessageStore) SaveMessageAttachments(ctx context.Context, messageID int32, attachments []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessageAttachments", ctx, messageID, attachments)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessageAttachments indicates an expected call of SaveMessageAttachments.
func (mr *MockMessageStoreMockRecorder) SaveMessageAttachments(ctx, messageID, attachments interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessageAttachments", reflect.TypeOf((*MockMessageStore)(nil).SaveMessageAttachments), ctx, messageID, attachments)
}
