local   all             all                                     trust

host    vk              main_user       172.18.0.0/16    md5
host    vk              auth_user       172.18.0.0/16    md5
host    vk              profile_user    172.18.0.0/16    md5
host    vk              friend_user     172.18.0.0/16    md5

host    all             postgres        172.18.0.0/16    md5
