// Code generated by MockGen. DO NOT EDIT.
// Source: domain/friend.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFriendService is a mock of FriendService interface.
type MockFriendService struct {
	ctrl     *gomock.Controller
	recorder *MockFriendServiceMockRecorder
}

// MockFriendServiceMockRecorder is the mock recorder for MockFriendService.
type MockFriendServiceMockRecorder struct {
	mock *MockFriendService
}

// NewMockFriendService creates a new mock instance.
func NewMockFriendService(ctrl *gomock.Controller) *MockFriendService {
	mock := &MockFriendService{ctrl: ctrl}
	mock.recorder = &MockFriendServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendService) EXPECT() *MockFriendServiceMockRecorder {
	return m.recorder
}

// AcceptFriendRequest mocks base method.
func (m *MockFriendService) AcceptFriendRequest(ctx context.Context, userID, friendID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFriendRequest", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFriendRequest indicates an expected call of AcceptFriendRequest.
func (mr *MockFriendServiceMockRecorder) AcceptFriendRequest(ctx, userID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendRequest", reflect.TypeOf((*MockFriendService)(nil).AcceptFriendRequest), ctx, userID, friendID)
}

// CountUserRelations mocks base method.
func (m *MockFriendService) CountUserRelations(ctx context.Context, userID int32) (*domain.UserRelationsCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserRelations", ctx, userID)
	ret0, _ := ret[0].(*domain.UserRelationsCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserRelations indicates an expected call of CountUserRelations.
func (mr *MockFriendServiceMockRecorder) CountUserRelations(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserRelations", reflect.TypeOf((*MockFriendService)(nil).CountUserRelations), ctx, userID)
}

// GetAllUsers mocks base method.
func (m *MockFriendService) GetAllUsers(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.ShortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, userID, params)
	ret0, _ := ret[0].([]domain.ShortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockFriendServiceMockRecorder) GetAllUsers(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockFriendService)(nil).GetAllUsers), ctx, userID, params)
}

// GetFriendRequests mocks base method.
func (m *MockFriendService) GetFriendRequests(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.ShortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendRequests", ctx, userID, params)
	ret0, _ := ret[0].([]domain.ShortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockFriendServiceMockRecorder) GetFriendRequests(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockFriendService)(nil).GetFriendRequests), ctx, userID, params)
}

// GetFriends mocks base method.
func (m *MockFriendService) GetFriends(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.ShortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriends", ctx, userID, params)
	ret0, _ := ret[0].([]domain.ShortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriends indicates an expected call of GetFriends.
func (mr *MockFriendServiceMockRecorder) GetFriends(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriends", reflect.TypeOf((*MockFriendService)(nil).GetFriends), ctx, userID, params)
}

// GetFriendshipStatus mocks base method.
func (m *MockFriendService) GetFriendshipStatus(ctx context.Context, userID, friendID int32) (domain.FriendshipStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipStatus", ctx, userID, friendID)
	ret0, _ := ret[0].(domain.FriendshipStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipStatus indicates an expected call of GetFriendshipStatus.
func (mr *MockFriendServiceMockRecorder) GetFriendshipStatus(ctx, userID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipStatus", reflect.TypeOf((*MockFriendService)(nil).GetFriendshipStatus), ctx, userID, friendID)
}

// GetSentRequests mocks base method.
func (m *MockFriendService) GetSentRequests(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.ShortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentRequests", ctx, userID, params)
	ret0, _ := ret[0].([]domain.ShortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentRequests indicates an expected call of GetSentRequests.
func (mr *MockFriendServiceMockRecorder) GetSentRequests(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentRequests", reflect.TypeOf((*MockFriendService)(nil).GetSentRequests), ctx, userID, params)
}

// RejectFriendRequest mocks base method.
func (m *MockFriendService) RejectFriendRequest(ctx context.Context, userID, friendID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectFriendRequest", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectFriendRequest indicates an expected call of RejectFriendRequest.
func (mr *MockFriendServiceMockRecorder) RejectFriendRequest(ctx, userID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectFriendRequest", reflect.TypeOf((*MockFriendService)(nil).RejectFriendRequest), ctx, userID, friendID)
}

// RemoveFriend mocks base method.
func (m *MockFriendService) RemoveFriend(ctx context.Context, userID, friendID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFriend indicates an expected call of RemoveFriend.
func (mr *MockFriendServiceMockRecorder) RemoveFriend(ctx, userID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriend", reflect.TypeOf((*MockFriendService)(nil).RemoveFriend), ctx, userID, friendID)
}

// SearchShortProfilesByFullNameAndRelationType mocks base method.
func (m *MockFriendService) SearchShortProfilesByFullNameAndRelationType(ctx context.Context, userID int32, params domain.PaginateQueryParams, fullName string, fType domain.FriendshipCountType) ([]domain.ShortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchShortProfilesByFullNameAndRelationType", ctx, userID, params, fullName, fType)
	ret0, _ := ret[0].([]domain.ShortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchShortProfilesByFullNameAndRelationType indicates an expected call of SearchShortProfilesByFullNameAndRelationType.
func (mr *MockFriendServiceMockRecorder) SearchShortProfilesByFullNameAndRelationType(ctx, userID, params, fullName, fType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchShortProfilesByFullNameAndRelationType", reflect.TypeOf((*MockFriendService)(nil).SearchShortProfilesByFullNameAndRelationType), ctx, userID, params, fullName, fType)
}

// SendFriendRequest mocks base method.
func (m *MockFriendService) SendFriendRequest(ctx context.Context, actionUserID, targetUserID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", ctx, actionUserID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockFriendServiceMockRecorder) SendFriendRequest(ctx, actionUserID, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockFriendService)(nil).SendFriendRequest), ctx, actionUserID, targetUserID)
}

// MockFriendStore is a mock of FriendStore interface.
type MockFriendStore struct {
	ctrl     *gomock.Controller
	recorder *MockFriendStoreMockRecorder
}

// MockFriendStoreMockRecorder is the mock recorder for MockFriendStore.
type MockFriendStoreMockRecorder struct {
	mock *MockFriendStore
}

// NewMockFriendStore creates a new mock instance.
func NewMockFriendStore(ctrl *gomock.Controller) *MockFriendStore {
	mock := &MockFriendStore{ctrl: ctrl}
	mock.recorder = &MockFriendStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendStore) EXPECT() *MockFriendStoreMockRecorder {
	return m.recorder
}

// AreFriends mocks base method.
func (m *MockFriendStore) AreFriends(ctx context.Context, userID1, userID2 int32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreFriends", ctx, userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreFriends indicates an expected call of AreFriends.
func (mr *MockFriendStoreMockRecorder) AreFriends(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreFriends", reflect.TypeOf((*MockFriendStore)(nil).AreFriends), ctx, userID1, userID2)
}

// CountUserRelations mocks base method.
func (m *MockFriendStore) CountUserRelations(ctx context.Context, userID int32) (*domain.UserRelationsCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserRelations", ctx, userID)
	ret0, _ := ret[0].(*domain.UserRelationsCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserRelations indicates an expected call of CountUserRelations.
func (mr *MockFriendStoreMockRecorder) CountUserRelations(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserRelations", reflect.TypeOf((*MockFriendStore)(nil).CountUserRelations), ctx, userID)
}

// CreateFriendship mocks base method.
func (m *MockFriendStore) CreateFriendship(ctx context.Context, actionUserID, targetUserID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFriendship", ctx, actionUserID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFriendship indicates an expected call of CreateFriendship.
func (mr *MockFriendStoreMockRecorder) CreateFriendship(ctx, actionUserID, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFriendship", reflect.TypeOf((*MockFriendStore)(nil).CreateFriendship), ctx, actionUserID, targetUserID)
}

// DeleteFriendship mocks base method.
func (m *MockFriendStore) DeleteFriendship(ctx context.Context, userID1, userID2 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriendship", ctx, userID1, userID2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriendship indicates an expected call of DeleteFriendship.
func (mr *MockFriendStoreMockRecorder) DeleteFriendship(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriendship", reflect.TypeOf((*MockFriendStore)(nil).DeleteFriendship), ctx, userID1, userID2)
}

// GetAllUsers mocks base method.
func (m *MockFriendStore) GetAllUsers(ctx context.Context, userID int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, userID)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockFriendStoreMockRecorder) GetAllUsers(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockFriendStore)(nil).GetAllUsers), ctx, userID)
}

// GetFriendship mocks base method.
func (m *MockFriendStore) GetFriendship(ctx context.Context, userID1, userID2 int32) (*domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendship", ctx, userID1, userID2)
	ret0, _ := ret[0].(*domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendship indicates an expected call of GetFriendship.
func (mr *MockFriendStoreMockRecorder) GetFriendship(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendship", reflect.TypeOf((*MockFriendStore)(nil).GetFriendship), ctx, userID1, userID2)
}

// GetFriendshipRequests mocks base method.
func (m *MockFriendStore) GetFriendshipRequests(ctx context.Context, userID, limit, offset int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipRequests", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipRequests indicates an expected call of GetFriendshipRequests.
func (mr *MockFriendStoreMockRecorder) GetFriendshipRequests(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipRequests", reflect.TypeOf((*MockFriendStore)(nil).GetFriendshipRequests), ctx, userID, limit, offset)
}

// GetFriendshipStatus mocks base method.
func (m *MockFriendStore) GetFriendshipStatus(ctx context.Context, userID1, userID2 int32) (domain.FriendshipStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipStatus", ctx, userID1, userID2)
	ret0, _ := ret[0].(domain.FriendshipStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipStatus indicates an expected call of GetFriendshipStatus.
func (mr *MockFriendStoreMockRecorder) GetFriendshipStatus(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipStatus", reflect.TypeOf((*MockFriendStore)(nil).GetFriendshipStatus), ctx, userID1, userID2)
}

// GetSentRequests mocks base method.
func (m *MockFriendStore) GetSentRequests(ctx context.Context, userID, limit, offset int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentRequests", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentRequests indicates an expected call of GetSentRequests.
func (mr *MockFriendStoreMockRecorder) GetSentRequests(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentRequests", reflect.TypeOf((*MockFriendStore)(nil).GetSentRequests), ctx, userID, limit, offset)
}

// GetUserFriends mocks base method.
func (m *MockFriendStore) GetUserFriends(ctx context.Context, userID, limit, offset int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFriends", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFriends indicates an expected call of GetUserFriends.
func (mr *MockFriendStoreMockRecorder) GetUserFriends(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFriends", reflect.TypeOf((*MockFriendStore)(nil).GetUserFriends), ctx, userID, limit, offset)
}

// GetUserIDsByFriendType mocks base method.
func (m *MockFriendStore) GetUserIDsByFriendType(ctx context.Context, userID int32, fType domain.FriendshipCountType) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDsByFriendType", ctx, userID, fType)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDsByFriendType indicates an expected call of GetUserIDsByFriendType.
func (mr *MockFriendStoreMockRecorder) GetUserIDsByFriendType(ctx, userID, fType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDsByFriendType", reflect.TypeOf((*MockFriendStore)(nil).GetUserIDsByFriendType), ctx, userID, fType)
}

// UpdateFriendshipStatus mocks base method.
func (m *MockFriendStore) UpdateFriendshipStatus(ctx context.Context, actionUserID, targetUserID int32, status domain.FriendshipStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFriendshipStatus", ctx, actionUserID, targetUserID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFriendshipStatus indicates an expected call of UpdateFriendshipStatus.
func (mr *MockFriendStoreMockRecorder) UpdateFriendshipStatus(ctx, actionUserID, targetUserID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFriendshipStatus", reflect.TypeOf((*MockFriendStore)(nil).UpdateFriendshipStatus), ctx, actionUserID, targetUserID, status)
}
