// Code generated by MockGen. DO NOT EDIT.
// Source: domain/community.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCommunityService is a mock of CommunityService interface.
type MockCommunityService struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityServiceMockRecorder
}

// MockCommunityServiceMockRecorder is the mock recorder for MockCommunityService.
type MockCommunityServiceMockRecorder struct {
	mock *MockCommunityService
}

// NewMockCommunityService creates a new mock instance.
func NewMockCommunityService(ctrl *gomock.Controller) *MockCommunityService {
	mock := &MockCommunityService{ctrl: ctrl}
	mock.recorder = &MockCommunityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityService) EXPECT() *MockCommunityServiceMockRecorder {
	return m.recorder
}

// CreateCommunity mocks base method.
func (m *MockCommunityService) CreateCommunity(ctx context.Context, userID int32, req domain.CommunityRequest, avatarFiles, coverFiles []*domain.File) (*domain.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommunity", ctx, userID, req, avatarFiles, coverFiles)
	ret0, _ := ret[0].(*domain.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommunity indicates an expected call of CreateCommunity.
func (mr *MockCommunityServiceMockRecorder) CreateCommunity(ctx, userID, req, avatarFiles, coverFiles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommunity", reflect.TypeOf((*MockCommunityService)(nil).CreateCommunity), ctx, userID, req, avatarFiles, coverFiles)
}

// DeleteCommunity mocks base method.
func (m *MockCommunityService) DeleteCommunity(ctx context.Context, communityID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunity", ctx, communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunity indicates an expected call of DeleteCommunity.
func (mr *MockCommunityServiceMockRecorder) DeleteCommunity(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunity", reflect.TypeOf((*MockCommunityService)(nil).DeleteCommunity), ctx, communityID, userID)
}

// GetCommunity mocks base method.
func (m *MockCommunityService) GetCommunity(ctx context.Context, userID, communityID int32) (*domain.CommunityForView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunity", ctx, userID, communityID)
	ret0, _ := ret[0].(*domain.CommunityForView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunity indicates an expected call of GetCommunity.
func (mr *MockCommunityServiceMockRecorder) GetCommunity(ctx, userID, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunity", reflect.TypeOf((*MockCommunityService)(nil).GetCommunity), ctx, userID, communityID)
}

// GetCommunitySubscribers mocks base method.
func (m *MockCommunityService) GetCommunitySubscribers(ctx context.Context, communityID int32, params domain.PaginateQueryParams) ([]domain.CommunitySubscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunitySubscribers", ctx, communityID, params)
	ret0, _ := ret[0].([]domain.CommunitySubscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunitySubscribers indicates an expected call of GetCommunitySubscribers.
func (mr *MockCommunityServiceMockRecorder) GetCommunitySubscribers(ctx, communityID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunitySubscribers", reflect.TypeOf((*MockCommunityService)(nil).GetCommunitySubscribers), ctx, communityID, params)
}

// GetCreatedCommunities mocks base method.
func (m *MockCommunityService) GetCreatedCommunities(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.CommunityForMyCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatedCommunities", ctx, userID, params)
	ret0, _ := ret[0].([]domain.CommunityForMyCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatedCommunities indicates an expected call of GetCreatedCommunities.
func (mr *MockCommunityServiceMockRecorder) GetCreatedCommunities(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatedCommunities", reflect.TypeOf((*MockCommunityService)(nil).GetCreatedCommunities), ctx, userID, params)
}

// GetOtherCommunities mocks base method.
func (m *MockCommunityService) GetOtherCommunities(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOtherCommunities", ctx, userID, params)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOtherCommunities indicates an expected call of GetOtherCommunities.
func (mr *MockCommunityServiceMockRecorder) GetOtherCommunities(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOtherCommunities", reflect.TypeOf((*MockCommunityService)(nil).GetOtherCommunities), ctx, userID, params)
}

// GetUserCommunities mocks base method.
func (m *MockCommunityService) GetUserCommunities(ctx context.Context, userID int32, params domain.PaginateQueryParams) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCommunities", ctx, userID, params)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCommunities indicates an expected call of GetUserCommunities.
func (mr *MockCommunityServiceMockRecorder) GetUserCommunities(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCommunities", reflect.TypeOf((*MockCommunityService)(nil).GetUserCommunities), ctx, userID, params)
}

// GetUserCommunitiesByID mocks base method.
func (m *MockCommunityService) GetUserCommunitiesByID(ctx context.Context, targetUserID int32, params domain.PaginateQueryParams) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCommunitiesByID", ctx, targetUserID, params)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCommunitiesByID indicates an expected call of GetUserCommunitiesByID.
func (mr *MockCommunityServiceMockRecorder) GetUserCommunitiesByID(ctx, targetUserID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCommunitiesByID", reflect.TypeOf((*MockCommunityService)(nil).GetUserCommunitiesByID), ctx, targetUserID, params)
}

// GetUserSubscribedCommunityIDs mocks base method.
func (m *MockCommunityService) GetUserSubscribedCommunityIDs(ctx context.Context, targetUserID int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSubscribedCommunityIDs", ctx, targetUserID)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSubscribedCommunityIDs indicates an expected call of GetUserSubscribedCommunityIDs.
func (mr *MockCommunityServiceMockRecorder) GetUserSubscribedCommunityIDs(ctx, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSubscribedCommunityIDs", reflect.TypeOf((*MockCommunityService)(nil).GetUserSubscribedCommunityIDs), ctx, targetUserID)
}

// SearchShortCommunityByNameAndType mocks base method.
func (m *MockCommunityService) SearchShortCommunityByNameAndType(ctx context.Context, userID int32, params domain.PaginateQueryParams, name string, cType domain.CommunityType) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchShortCommunityByNameAndType", ctx, userID, params, name, cType)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchShortCommunityByNameAndType indicates an expected call of SearchShortCommunityByNameAndType.
func (mr *MockCommunityServiceMockRecorder) SearchShortCommunityByNameAndType(ctx, userID, params, name, cType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchShortCommunityByNameAndType", reflect.TypeOf((*MockCommunityService)(nil).SearchShortCommunityByNameAndType), ctx, userID, params, name, cType)
}

// Subscribe mocks base method.
func (m *MockCommunityService) Subscribe(ctx context.Context, communityID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockCommunityServiceMockRecorder) Subscribe(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockCommunityService)(nil).Subscribe), ctx, communityID, userID)
}

// Unsubscribe mocks base method.
func (m *MockCommunityService) Unsubscribe(ctx context.Context, communityID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockCommunityServiceMockRecorder) Unsubscribe(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockCommunityService)(nil).Unsubscribe), ctx, communityID, userID)
}

// UpdateCommunity mocks base method.
func (m *MockCommunityService) UpdateCommunity(ctx context.Context, communityID, userID int32, req domain.CommunityRequest, avatarFiles, coverFiles []*domain.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", ctx, communityID, userID, req, avatarFiles, coverFiles)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockCommunityServiceMockRecorder) UpdateCommunity(ctx, communityID, userID, req, avatarFiles, coverFiles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockCommunityService)(nil).UpdateCommunity), ctx, communityID, userID, req, avatarFiles, coverFiles)
}

// MockElasticCommunityStore is a mock of ElasticCommunityStore interface.
type MockElasticCommunityStore struct {
	ctrl     *gomock.Controller
	recorder *MockElasticCommunityStoreMockRecorder
}

// MockElasticCommunityStoreMockRecorder is the mock recorder for MockElasticCommunityStore.
type MockElasticCommunityStoreMockRecorder struct {
	mock *MockElasticCommunityStore
}

// NewMockElasticCommunityStore creates a new mock instance.
func NewMockElasticCommunityStore(ctrl *gomock.Controller) *MockElasticCommunityStore {
	mock := &MockElasticCommunityStore{ctrl: ctrl}
	mock.recorder = &MockElasticCommunityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElasticCommunityStore) EXPECT() *MockElasticCommunityStoreMockRecorder {
	return m.recorder
}

// CreateCommunity mocks base method.
func (m *MockElasticCommunityStore) CreateCommunity(ctx context.Context, name string, communityID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommunity", ctx, name, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCommunity indicates an expected call of CreateCommunity.
func (mr *MockElasticCommunityStoreMockRecorder) CreateCommunity(ctx, name, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommunity", reflect.TypeOf((*MockElasticCommunityStore)(nil).CreateCommunity), ctx, name, communityID)
}

// DeleteCommunity mocks base method.
func (m *MockElasticCommunityStore) DeleteCommunity(ctx context.Context, communityID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunity", ctx, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunity indicates an expected call of DeleteCommunity.
func (mr *MockElasticCommunityStoreMockRecorder) DeleteCommunity(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunity", reflect.TypeOf((*MockElasticCommunityStore)(nil).DeleteCommunity), ctx, communityID)
}

// SearchCommunityIDsByName mocks base method.
func (m *MockElasticCommunityStore) SearchCommunityIDsByName(ctx context.Context, name string, filterIDs []int32, isTerms bool, limit, offset int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCommunityIDsByName", ctx, name, filterIDs, isTerms, limit, offset)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCommunityIDsByName indicates an expected call of SearchCommunityIDsByName.
func (mr *MockElasticCommunityStoreMockRecorder) SearchCommunityIDsByName(ctx, name, filterIDs, isTerms, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCommunityIDsByName", reflect.TypeOf((*MockElasticCommunityStore)(nil).SearchCommunityIDsByName), ctx, name, filterIDs, isTerms, limit, offset)
}

// UpdateCommunity mocks base method.
func (m *MockElasticCommunityStore) UpdateCommunity(ctx context.Context, name string, communityID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", ctx, name, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockElasticCommunityStoreMockRecorder) UpdateCommunity(ctx, name, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockElasticCommunityStore)(nil).UpdateCommunity), ctx, name, communityID)
}

// MockCommunityStore is a mock of CommunityStore interface.
type MockCommunityStore struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityStoreMockRecorder
}

// MockCommunityStoreMockRecorder is the mock recorder for MockCommunityStore.
type MockCommunityStoreMockRecorder struct {
	mock *MockCommunityStore
}

// NewMockCommunityStore creates a new mock instance.
func NewMockCommunityStore(ctrl *gomock.Controller) *MockCommunityStore {
	mock := &MockCommunityStore{ctrl: ctrl}
	mock.recorder = &MockCommunityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityStore) EXPECT() *MockCommunityStoreMockRecorder {
	return m.recorder
}

// CreateCommunity mocks base method.
func (m *MockCommunityStore) CreateCommunity(ctx context.Context, community *domain.Community) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommunity", ctx, community)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCommunity indicates an expected call of CreateCommunity.
func (mr *MockCommunityStoreMockRecorder) CreateCommunity(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommunity", reflect.TypeOf((*MockCommunityStore)(nil).CreateCommunity), ctx, community)
}

// DeleteCommunity mocks base method.
func (m *MockCommunityStore) DeleteCommunity(ctx context.Context, id, creatorID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunity", ctx, id, creatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunity indicates an expected call of DeleteCommunity.
func (mr *MockCommunityStoreMockRecorder) DeleteCommunity(ctx, id, creatorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunity", reflect.TypeOf((*MockCommunityStore)(nil).DeleteCommunity), ctx, id, creatorID)
}

// GetCommunitiesByIDs mocks base method.
func (m *MockCommunityStore) GetCommunitiesByIDs(ctx context.Context, communityIDs []int32) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunitiesByIDs", ctx, communityIDs)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunitiesByIDs indicates an expected call of GetCommunitiesByIDs.
func (mr *MockCommunityStoreMockRecorder) GetCommunitiesByIDs(ctx, communityIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunitiesByIDs", reflect.TypeOf((*MockCommunityStore)(nil).GetCommunitiesByIDs), ctx, communityIDs)
}

// GetCommunityByID mocks base method.
func (m *MockCommunityStore) GetCommunityByID(ctx context.Context, id int32) (*domain.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityByID", ctx, id)
	ret0, _ := ret[0].(*domain.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityByID indicates an expected call of GetCommunityByID.
func (mr *MockCommunityStoreMockRecorder) GetCommunityByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityByID", reflect.TypeOf((*MockCommunityStore)(nil).GetCommunityByID), ctx, id)
}

// GetCommunitySubscribers mocks base method.
func (m *MockCommunityStore) GetCommunitySubscribers(ctx context.Context, communityID, limit, offset int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunitySubscribers", ctx, communityID, limit, offset)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunitySubscribers indicates an expected call of GetCommunitySubscribers.
func (mr *MockCommunityStoreMockRecorder) GetCommunitySubscribers(ctx, communityID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunitySubscribers", reflect.TypeOf((*MockCommunityStore)(nil).GetCommunitySubscribers), ctx, communityID, limit, offset)
}

// GetCreatedCommunities mocks base method.
func (m *MockCommunityStore) GetCreatedCommunities(ctx context.Context, userID, limit, offset int32) ([]domain.CommunityForMyCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatedCommunities", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.CommunityForMyCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatedCommunities indicates an expected call of GetCreatedCommunities.
func (mr *MockCommunityStoreMockRecorder) GetCreatedCommunities(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatedCommunities", reflect.TypeOf((*MockCommunityStore)(nil).GetCreatedCommunities), ctx, userID, limit, offset)
}

// GetOtherCommunities mocks base method.
func (m *MockCommunityStore) GetOtherCommunities(ctx context.Context, userID, limit, offset int32) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOtherCommunities", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOtherCommunities indicates an expected call of GetOtherCommunities.
func (mr *MockCommunityStoreMockRecorder) GetOtherCommunities(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOtherCommunities", reflect.TypeOf((*MockCommunityStore)(nil).GetOtherCommunities), ctx, userID, limit, offset)
}

// GetUserCommunities mocks base method.
func (m *MockCommunityStore) GetUserCommunities(ctx context.Context, userID, limit, offset int32) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCommunities", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCommunities indicates an expected call of GetUserCommunities.
func (mr *MockCommunityStoreMockRecorder) GetUserCommunities(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCommunities", reflect.TypeOf((*MockCommunityStore)(nil).GetUserCommunities), ctx, userID, limit, offset)
}

// GetUserCommunitiesByID mocks base method.
func (m *MockCommunityStore) GetUserCommunitiesByID(ctx context.Context, targetUserID, limit, offset int32) ([]domain.ShortCommunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCommunitiesByID", ctx, targetUserID, limit, offset)
	ret0, _ := ret[0].([]domain.ShortCommunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCommunitiesByID indicates an expected call of GetUserCommunitiesByID.
func (mr *MockCommunityStoreMockRecorder) GetUserCommunitiesByID(ctx, targetUserID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCommunitiesByID", reflect.TypeOf((*MockCommunityStore)(nil).GetUserCommunitiesByID), ctx, targetUserID, limit, offset)
}

// GetUserSubscribedCommunityIDs mocks base method.
func (m *MockCommunityStore) GetUserSubscribedCommunityIDs(ctx context.Context, targetUserID int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSubscribedCommunityIDs", ctx, targetUserID)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSubscribedCommunityIDs indicates an expected call of GetUserSubscribedCommunityIDs.
func (mr *MockCommunityStoreMockRecorder) GetUserSubscribedCommunityIDs(ctx, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSubscribedCommunityIDs", reflect.TypeOf((*MockCommunityStore)(nil).GetUserSubscribedCommunityIDs), ctx, targetUserID)
}

// IsSubscribed mocks base method.
func (m *MockCommunityStore) IsSubscribed(ctx context.Context, communityID, userID int32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscribed", ctx, communityID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubscribed indicates an expected call of IsSubscribed.
func (mr *MockCommunityStoreMockRecorder) IsSubscribed(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscribed", reflect.TypeOf((*MockCommunityStore)(nil).IsSubscribed), ctx, communityID, userID)
}

// Subscribe mocks base method.
func (m *MockCommunityStore) Subscribe(ctx context.Context, communityID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockCommunityStoreMockRecorder) Subscribe(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockCommunityStore)(nil).Subscribe), ctx, communityID, userID)
}

// Unsubscribe mocks base method.
func (m *MockCommunityStore) Unsubscribe(ctx context.Context, communityID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockCommunityStoreMockRecorder) Unsubscribe(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockCommunityStore)(nil).Unsubscribe), ctx, communityID, userID)
}

// UpdateCommunity mocks base method.
func (m *MockCommunityStore) UpdateCommunity(ctx context.Context, community *domain.Community) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", ctx, community)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockCommunityStoreMockRecorder) UpdateCommunity(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockCommunityStore)(nil).UpdateCommunity), ctx, community)
}
