// Code generated by MockGen. DO NOT EDIT.
// Source: domain/comment.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentService) CreateComment(ctx context.Context, userID int32, req domain.CommentCreateRequest) (*domain.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, userID, req)
	ret0, _ := ret[0].(*domain.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceMockRecorder) CreateComment(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentService)(nil).CreateComment), ctx, userID, req)
}

// DeleteComment mocks base method.
func (m *MockCommentService) DeleteComment(ctx context.Context, commentID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, commentID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentServiceMockRecorder) DeleteComment(ctx, commentID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentService)(nil).DeleteComment), ctx, commentID, userID)
}

// GetComment mocks base method.
func (m *MockCommentService) GetComment(ctx context.Context, userID, commentID int32) (*domain.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, userID, commentID)
	ret0, _ := ret[0].(*domain.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCommentServiceMockRecorder) GetComment(ctx, userID, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCommentService)(nil).GetComment), ctx, userID, commentID)
}

// GetPostComments mocks base method.
func (m *MockCommentService) GetPostComments(ctx context.Context, userID, postID int32, params domain.PaginateQueryParams) ([]domain.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostComments", ctx, userID, postID, params)
	ret0, _ := ret[0].([]domain.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostComments indicates an expected call of GetPostComments.
func (mr *MockCommentServiceMockRecorder) GetPostComments(ctx, userID, postID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostComments", reflect.TypeOf((*MockCommentService)(nil).GetPostComments), ctx, userID, postID, params)
}

// GetPostCommentsCount mocks base method.
func (m *MockCommentService) GetPostCommentsCount(ctx context.Context, postID int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostCommentsCount", ctx, postID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostCommentsCount indicates an expected call of GetPostCommentsCount.
func (mr *MockCommentServiceMockRecorder) GetPostCommentsCount(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostCommentsCount", reflect.TypeOf((*MockCommentService)(nil).GetPostCommentsCount), ctx, postID)
}

// UpdateComment mocks base method.
func (m *MockCommentService) UpdateComment(ctx context.Context, commentID, userID int32, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, commentID, userID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentServiceMockRecorder) UpdateComment(ctx, commentID, userID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentService)(nil).UpdateComment), ctx, commentID, userID, text)
}

// MockCommentStore is a mock of CommentStore interface.
type MockCommentStore struct {
	ctrl     *gomock.Controller
	recorder *MockCommentStoreMockRecorder
}

// MockCommentStoreMockRecorder is the mock recorder for MockCommentStore.
type MockCommentStoreMockRecorder struct {
	mock *MockCommentStore
}

// NewMockCommentStore creates a new mock instance.
func NewMockCommentStore(ctrl *gomock.Controller) *MockCommentStore {
	mock := &MockCommentStore{ctrl: ctrl}
	mock.recorder = &MockCommentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentStore) EXPECT() *MockCommentStoreMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentStore) CreateComment(ctx context.Context, comment *domain.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentStoreMockRecorder) CreateComment(ctx, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentStore)(nil).CreateComment), ctx, comment)
}

// DeleteComment mocks base method.
func (m *MockCommentStore) DeleteComment(ctx context.Context, id, authorID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, id, authorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentStoreMockRecorder) DeleteComment(ctx, id, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentStore)(nil).DeleteComment), ctx, id, authorID)
}

// GetCommentByID mocks base method.
func (m *MockCommentStore) GetCommentByID(ctx context.Context, id int32) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentByID indicates an expected call of GetCommentByID.
func (mr *MockCommentStoreMockRecorder) GetCommentByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentByID", reflect.TypeOf((*MockCommentStore)(nil).GetCommentByID), ctx, id)
}

// GetCommentsByPost mocks base method.
func (m *MockCommentStore) GetCommentsByPost(ctx context.Context, postID, limit, offset int32) ([]domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByPost", ctx, postID, limit, offset)
	ret0, _ := ret[0].([]domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByPost indicates an expected call of GetCommentsByPost.
func (mr *MockCommentStoreMockRecorder) GetCommentsByPost(ctx, postID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByPost", reflect.TypeOf((*MockCommentStore)(nil).GetCommentsByPost), ctx, postID, limit, offset)
}

// GetPostCommentsCount mocks base method.
func (m *MockCommentStore) GetPostCommentsCount(ctx context.Context, postID int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostCommentsCount", ctx, postID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostCommentsCount indicates an expected call of GetPostCommentsCount.
func (mr *MockCommentStoreMockRecorder) GetPostCommentsCount(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostCommentsCount", reflect.TypeOf((*MockCommentStore)(nil).GetPostCommentsCount), ctx, postID)
}

// UpdateComment mocks base method.
func (m *MockCommentStore) UpdateComment(ctx context.Context, comment *domain.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentStoreMockRecorder) UpdateComment(ctx, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentStore)(nil).UpdateComment), ctx, comment)
}
