// Code generated by MockGen. DO NOT EDIT.
// Source: domain/friend.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFriendStore is a mock of FriendStore interface.
type MockFriendStore struct {
	ctrl     *gomock.Controller
	recorder *MockFriendStoreMockRecorder
}

// MockFriendStoreMockRecorder is the mock recorder for MockFriendStore.
type MockFriendStoreMockRecorder struct {
	mock *MockFriendStore
}

// NewMockFriendStore creates a new mock instance.
func NewMockFriendStore(ctrl *gomock.Controller) *MockFriendStore {
	mock := &MockFriendStore{ctrl: ctrl}
	mock.recorder = &MockFriendStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendStore) EXPECT() *MockFriendStoreMockRecorder {
	return m.recorder
}

// AreFriends mocks base method.
func (m *MockFriendStore) AreFriends(ctx context.Context, userID1, userID2 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreFriends", ctx, userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreFriends indicates an expected call of AreFriends.
func (mr *MockFriendStoreMockRecorder) AreFriends(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreFriends", reflect.TypeOf((*MockFriendStore)(nil).AreFriends), ctx, userID1, userID2)
}

// CreateFriendship mocks base method.
func (m *MockFriendStore) CreateFriendship(ctx context.Context, actionUserID, targetUserID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFriendship", ctx, actionUserID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFriendship indicates an expected call of CreateFriendship.
func (mr *MockFriendStoreMockRecorder) CreateFriendship(ctx, actionUserID, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFriendship", reflect.TypeOf((*MockFriendStore)(nil).CreateFriendship), ctx, actionUserID, targetUserID)
}

// DeleteFriendship mocks base method.
func (m *MockFriendStore) DeleteFriendship(ctx context.Context, userID1, userID2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriendship", ctx, userID1, userID2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriendship indicates an expected call of DeleteFriendship.
func (mr *MockFriendStoreMockRecorder) DeleteFriendship(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriendship", reflect.TypeOf((*MockFriendStore)(nil).DeleteFriendship), ctx, userID1, userID2)
}

// GetFriendship mocks base method.
func (m *MockFriendStore) GetFriendship(ctx context.Context, userID1, userID2 int) (*domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendship", ctx, userID1, userID2)
	ret0, _ := ret[0].(*domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendship indicates an expected call of GetFriendship.
func (mr *MockFriendStoreMockRecorder) GetFriendship(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendship", reflect.TypeOf((*MockFriendStore)(nil).GetFriendship), ctx, userID1, userID2)
}

// GetFriendshipRequests mocks base method.
func (m *MockFriendStore) GetFriendshipRequests(ctx context.Context, userID, page, limit int) ([]domain.FriendshipWithProfile, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipRequests", ctx, userID, page, limit)
	ret0, _ := ret[0].([]domain.FriendshipWithProfile)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFriendshipRequests indicates an expected call of GetFriendshipRequests.
func (mr *MockFriendStoreMockRecorder) GetFriendshipRequests(ctx, userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipRequests", reflect.TypeOf((*MockFriendStore)(nil).GetFriendshipRequests), ctx, userID, page, limit)
}

// GetFriendshipStatus mocks base method.
func (m *MockFriendStore) GetFriendshipStatus(ctx context.Context, userID1, userID2 int) (domain.FriendshipStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipStatus", ctx, userID1, userID2)
	ret0, _ := ret[0].(domain.FriendshipStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipStatus indicates an expected call of GetFriendshipStatus.
func (mr *MockFriendStoreMockRecorder) GetFriendshipStatus(ctx, userID1, userID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipStatus", reflect.TypeOf((*MockFriendStore)(nil).GetFriendshipStatus), ctx, userID1, userID2)
}

// GetSentRequests mocks base method.
func (m *MockFriendStore) GetSentRequests(ctx context.Context, userID, page, limit int) ([]domain.FriendshipWithProfile, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentRequests", ctx, userID, page, limit)
	ret0, _ := ret[0].([]domain.FriendshipWithProfile)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSentRequests indicates an expected call of GetSentRequests.
func (mr *MockFriendStoreMockRecorder) GetSentRequests(ctx, userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentRequests", reflect.TypeOf((*MockFriendStore)(nil).GetSentRequests), ctx, userID, page, limit)
}

// GetUserFriends mocks base method.
func (m *MockFriendStore) GetUserFriends(ctx context.Context, userID, page, limit int) ([]domain.ShortProfile, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFriends", ctx, userID, page, limit)
	ret0, _ := ret[0].([]domain.ShortProfile)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserFriends indicates an expected call of GetUserFriends.
func (mr *MockFriendStoreMockRecorder) GetUserFriends(ctx, userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFriends", reflect.TypeOf((*MockFriendStore)(nil).GetUserFriends), ctx, userID, page, limit)
}

// UpdateFriendshipStatus mocks base method.
func (m *MockFriendStore) UpdateFriendshipStatus(ctx context.Context, userID1, userID2 int, status domain.FriendshipStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFriendshipStatus", ctx, userID1, userID2, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFriendshipStatus indicates an expected call of UpdateFriendshipStatus.
func (mr *MockFriendStoreMockRecorder) UpdateFriendshipStatus(ctx, userID1, userID2, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFriendshipStatus", reflect.TypeOf((*MockFriendStore)(nil).UpdateFriendshipStatus), ctx, userID1, userID2, status)
}
