// Code generated by MockGen. DO NOT EDIT.
// Source: domain/profile.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	domain "project/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
}

// MockProfileServiceMockRecorder is the mock recorder for MockProfileService.
type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

// NewMockProfileService creates a new mock instance.
func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

// GetProfileByUserID mocks base method.
func (m *MockProfileService) GetProfileByUserID(ctx context.Context, userID int32) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUserID indicates an expected call of GetProfileByUserID.
func (mr *MockProfileServiceMockRecorder) GetProfileByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUserID", reflect.TypeOf((*MockProfileService)(nil).GetProfileByUserID), ctx, userID)
}

// UpdateAvatar mocks base method.
func (m *MockProfileService) UpdateAvatar(ctx context.Context, userID int32, files []*multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, files)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockProfileServiceMockRecorder) UpdateAvatar(ctx, userID, files interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockProfileService)(nil).UpdateAvatar), ctx, userID, files)
}

// UpdateHeader mocks base method.
func (m *MockProfileService) UpdateHeader(ctx context.Context, userID int32, files []*multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHeader", ctx, userID, files)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHeader indicates an expected call of UpdateHeader.
func (mr *MockProfileServiceMockRecorder) UpdateHeader(ctx, userID, files interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHeader", reflect.TypeOf((*MockProfileService)(nil).UpdateHeader), ctx, userID, files)
}

// UpdateProfile mocks base method.
func (m *MockProfileService) UpdateProfile(ctx context.Context, profile domain.Profile, userID int32, files []*multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, profile, userID, files)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileServiceMockRecorder) UpdateProfile(ctx, profile, userID, files interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileService)(nil).UpdateProfile), ctx, profile, userID, files)
}

// MockProfileStore is a mock of ProfileStore interface.
type MockProfileStore struct {
	ctrl     *gomock.Controller
	recorder *MockProfileStoreMockRecorder
}

// MockProfileStoreMockRecorder is the mock recorder for MockProfileStore.
type MockProfileStoreMockRecorder struct {
	mock *MockProfileStore
}

// NewMockProfileStore creates a new mock instance.
func NewMockProfileStore(ctrl *gomock.Controller) *MockProfileStore {
	mock := &MockProfileStore{ctrl: ctrl}
	mock.recorder = &MockProfileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileStore) EXPECT() *MockProfileStoreMockRecorder {
	return m.recorder
}

// GetAvatarByUserID mocks base method.
func (m *MockProfileStore) GetAvatarByUserID(ctx context.Context, userID int32) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarByUserID", ctx, userID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarByUserID indicates an expected call of GetAvatarByUserID.
func (mr *MockProfileStoreMockRecorder) GetAvatarByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarByUserID", reflect.TypeOf((*MockProfileStore)(nil).GetAvatarByUserID), ctx, userID)
}

// GetHeaderByUserID mocks base method.
func (m *MockProfileStore) GetHeaderByUserID(ctx context.Context, userID int32) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderByUserID", ctx, userID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderByUserID indicates an expected call of GetHeaderByUserID.
func (mr *MockProfileStoreMockRecorder) GetHeaderByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderByUserID", reflect.TypeOf((*MockProfileStore)(nil).GetHeaderByUserID), ctx, userID)
}

// GetProfileByUserID mocks base method.
func (m *MockProfileStore) GetProfileByUserID(ctx context.Context, userID int32) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUserID", ctx, userID)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUserID indicates an expected call of GetProfileByUserID.
func (mr *MockProfileStoreMockRecorder) GetProfileByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUserID", reflect.TypeOf((*MockProfileStore)(nil).GetProfileByUserID), ctx, userID)
}

// GetShortProfileByUserIDs mocks base method.
func (m *MockProfileStore) GetShortProfileByUserIDs(ctx context.Context, userIDs []int32) (map[int32]domain.ShortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortProfileByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[int32]domain.ShortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortProfileByUserIDs indicates an expected call of GetShortProfileByUserIDs.
func (mr *MockProfileStoreMockRecorder) GetShortProfileByUserIDs(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortProfileByUserIDs", reflect.TypeOf((*MockProfileStore)(nil).GetShortProfileByUserIDs), ctx, userIDs)
}

// UpdateAvatar mocks base method.
func (m *MockProfileStore) UpdateAvatar(ctx context.Context, avatarPath string, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, avatarPath, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockProfileStoreMockRecorder) UpdateAvatar(ctx, avatarPath, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockProfileStore)(nil).UpdateAvatar), ctx, avatarPath, userID)
}

// UpdateHeader mocks base method.
func (m *MockProfileStore) UpdateHeader(ctx context.Context, avatarPath string, UserID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHeader", ctx, avatarPath, UserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHeader indicates an expected call of UpdateHeader.
func (mr *MockProfileStoreMockRecorder) UpdateHeader(ctx, avatarPath, UserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHeader", reflect.TypeOf((*MockProfileStore)(nil).UpdateHeader), ctx, avatarPath, UserID)
}

// UpdateProfile mocks base method.
func (m *MockProfileStore) UpdateProfile(ctx context.Context, profile domain.Profile, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, profile, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileStoreMockRecorder) UpdateProfile(ctx, profile, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileStore)(nil).UpdateProfile), ctx, profile, userID)
}
