// Code generated by MockGen. DO NOT EDIT.
// Source: shared/pb/friend_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	pb "project/shared/pb"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockFriendServiceClient is a mock of FriendServiceClient interface.
type MockFriendServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFriendServiceClientMockRecorder
}

// MockFriendServiceClientMockRecorder is the mock recorder for MockFriendServiceClient.
type MockFriendServiceClientMockRecorder struct {
	mock *MockFriendServiceClient
}

// NewMockFriendServiceClient creates a new mock instance.
func NewMockFriendServiceClient(ctrl *gomock.Controller) *MockFriendServiceClient {
	mock := &MockFriendServiceClient{ctrl: ctrl}
	mock.recorder = &MockFriendServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendServiceClient) EXPECT() *MockFriendServiceClientMockRecorder {
	return m.recorder
}

// AcceptFriendRequest mocks base method.
func (m *MockFriendServiceClient) AcceptFriendRequest(ctx context.Context, in *pb.UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptFriendRequest", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptFriendRequest indicates an expected call of AcceptFriendRequest.
func (mr *MockFriendServiceClientMockRecorder) AcceptFriendRequest(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendRequest", reflect.TypeOf((*MockFriendServiceClient)(nil).AcceptFriendRequest), varargs...)
}

// CountUserRelations mocks base method.
func (m *MockFriendServiceClient) CountUserRelations(ctx context.Context, in *pb.CountUserRelationsRequest, opts ...grpc.CallOption) (*pb.UserRelationsCountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountUserRelations", varargs...)
	ret0, _ := ret[0].(*pb.UserRelationsCountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserRelations indicates an expected call of CountUserRelations.
func (mr *MockFriendServiceClientMockRecorder) CountUserRelations(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserRelations", reflect.TypeOf((*MockFriendServiceClient)(nil).CountUserRelations), varargs...)
}

// GetAllUsers mocks base method.
func (m *MockFriendServiceClient) GetAllUsers(ctx context.Context, in *pb.GetAllUsersRequest, opts ...grpc.CallOption) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllUsers", varargs...)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockFriendServiceClientMockRecorder) GetAllUsers(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockFriendServiceClient)(nil).GetAllUsers), varargs...)
}

// GetFriendRequests mocks base method.
func (m *MockFriendServiceClient) GetFriendRequests(ctx context.Context, in *pb.GetFriendRequestsRequest, opts ...grpc.CallOption) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFriendRequests", varargs...)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockFriendServiceClientMockRecorder) GetFriendRequests(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockFriendServiceClient)(nil).GetFriendRequests), varargs...)
}

// GetFriends mocks base method.
func (m *MockFriendServiceClient) GetFriends(ctx context.Context, in *pb.GetFriendsRequest, opts ...grpc.CallOption) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFriends", varargs...)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriends indicates an expected call of GetFriends.
func (mr *MockFriendServiceClientMockRecorder) GetFriends(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriends", reflect.TypeOf((*MockFriendServiceClient)(nil).GetFriends), varargs...)
}

// GetFriendshipStatus mocks base method.
func (m *MockFriendServiceClient) GetFriendshipStatus(ctx context.Context, in *pb.GetFriendshipStatusRequest, opts ...grpc.CallOption) (*pb.FriendshipStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFriendshipStatus", varargs...)
	ret0, _ := ret[0].(*pb.FriendshipStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipStatus indicates an expected call of GetFriendshipStatus.
func (mr *MockFriendServiceClientMockRecorder) GetFriendshipStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipStatus", reflect.TypeOf((*MockFriendServiceClient)(nil).GetFriendshipStatus), varargs...)
}

// GetSentRequests mocks base method.
func (m *MockFriendServiceClient) GetSentRequests(ctx context.Context, in *pb.GetSentRequestsRequest, opts ...grpc.CallOption) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSentRequests", varargs...)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentRequests indicates an expected call of GetSentRequests.
func (mr *MockFriendServiceClientMockRecorder) GetSentRequests(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentRequests", reflect.TypeOf((*MockFriendServiceClient)(nil).GetSentRequests), varargs...)
}

// RejectFriendRequest mocks base method.
func (m *MockFriendServiceClient) RejectFriendRequest(ctx context.Context, in *pb.UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RejectFriendRequest", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectFriendRequest indicates an expected call of RejectFriendRequest.
func (mr *MockFriendServiceClientMockRecorder) RejectFriendRequest(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectFriendRequest", reflect.TypeOf((*MockFriendServiceClient)(nil).RejectFriendRequest), varargs...)
}

// RemoveFriend mocks base method.
func (m *MockFriendServiceClient) RemoveFriend(ctx context.Context, in *pb.UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFriend", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFriend indicates an expected call of RemoveFriend.
func (mr *MockFriendServiceClientMockRecorder) RemoveFriend(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriend", reflect.TypeOf((*MockFriendServiceClient)(nil).RemoveFriend), varargs...)
}

// SearchShortProfilesByFullNameAndRelationType mocks base method.
func (m *MockFriendServiceClient) SearchShortProfilesByFullNameAndRelationType(ctx context.Context, in *pb.SearchProfilesRequest, opts ...grpc.CallOption) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchShortProfilesByFullNameAndRelationType", varargs...)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchShortProfilesByFullNameAndRelationType indicates an expected call of SearchShortProfilesByFullNameAndRelationType.
func (mr *MockFriendServiceClientMockRecorder) SearchShortProfilesByFullNameAndRelationType(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchShortProfilesByFullNameAndRelationType", reflect.TypeOf((*MockFriendServiceClient)(nil).SearchShortProfilesByFullNameAndRelationType), varargs...)
}

// SendFriendRequest mocks base method.
func (m *MockFriendServiceClient) SendFriendRequest(ctx context.Context, in *pb.SendFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendFriendRequest", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockFriendServiceClientMockRecorder) SendFriendRequest(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockFriendServiceClient)(nil).SendFriendRequest), varargs...)
}

// MockFriendServiceServer is a mock of FriendServiceServer interface.
type MockFriendServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockFriendServiceServerMockRecorder
}

// MockFriendServiceServerMockRecorder is the mock recorder for MockFriendServiceServer.
type MockFriendServiceServerMockRecorder struct {
	mock *MockFriendServiceServer
}

// NewMockFriendServiceServer creates a new mock instance.
func NewMockFriendServiceServer(ctrl *gomock.Controller) *MockFriendServiceServer {
	mock := &MockFriendServiceServer{ctrl: ctrl}
	mock.recorder = &MockFriendServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendServiceServer) EXPECT() *MockFriendServiceServerMockRecorder {
	return m.recorder
}

// AcceptFriendRequest mocks base method.
func (m *MockFriendServiceServer) AcceptFriendRequest(arg0 context.Context, arg1 *pb.UserIDsPair) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFriendRequest", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptFriendRequest indicates an expected call of AcceptFriendRequest.
func (mr *MockFriendServiceServerMockRecorder) AcceptFriendRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendRequest", reflect.TypeOf((*MockFriendServiceServer)(nil).AcceptFriendRequest), arg0, arg1)
}

// CountUserRelations mocks base method.
func (m *MockFriendServiceServer) CountUserRelations(arg0 context.Context, arg1 *pb.CountUserRelationsRequest) (*pb.UserRelationsCountsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserRelations", arg0, arg1)
	ret0, _ := ret[0].(*pb.UserRelationsCountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserRelations indicates an expected call of CountUserRelations.
func (mr *MockFriendServiceServerMockRecorder) CountUserRelations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserRelations", reflect.TypeOf((*MockFriendServiceServer)(nil).CountUserRelations), arg0, arg1)
}

// GetAllUsers mocks base method.
func (m *MockFriendServiceServer) GetAllUsers(arg0 context.Context, arg1 *pb.GetAllUsersRequest) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", arg0, arg1)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockFriendServiceServerMockRecorder) GetAllUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockFriendServiceServer)(nil).GetAllUsers), arg0, arg1)
}

// GetFriendRequests mocks base method.
func (m *MockFriendServiceServer) GetFriendRequests(arg0 context.Context, arg1 *pb.GetFriendRequestsRequest) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendRequests", arg0, arg1)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockFriendServiceServerMockRecorder) GetFriendRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockFriendServiceServer)(nil).GetFriendRequests), arg0, arg1)
}

// GetFriends mocks base method.
func (m *MockFriendServiceServer) GetFriends(arg0 context.Context, arg1 *pb.GetFriendsRequest) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriends", arg0, arg1)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriends indicates an expected call of GetFriends.
func (mr *MockFriendServiceServerMockRecorder) GetFriends(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriends", reflect.TypeOf((*MockFriendServiceServer)(nil).GetFriends), arg0, arg1)
}

// GetFriendshipStatus mocks base method.
func (m *MockFriendServiceServer) GetFriendshipStatus(arg0 context.Context, arg1 *pb.GetFriendshipStatusRequest) (*pb.FriendshipStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipStatus", arg0, arg1)
	ret0, _ := ret[0].(*pb.FriendshipStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipStatus indicates an expected call of GetFriendshipStatus.
func (mr *MockFriendServiceServerMockRecorder) GetFriendshipStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipStatus", reflect.TypeOf((*MockFriendServiceServer)(nil).GetFriendshipStatus), arg0, arg1)
}

// GetSentRequests mocks base method.
func (m *MockFriendServiceServer) GetSentRequests(arg0 context.Context, arg1 *pb.GetSentRequestsRequest) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentRequests", arg0, arg1)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentRequests indicates an expected call of GetSentRequests.
func (mr *MockFriendServiceServerMockRecorder) GetSentRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentRequests", reflect.TypeOf((*MockFriendServiceServer)(nil).GetSentRequests), arg0, arg1)
}

// RejectFriendRequest mocks base method.
func (m *MockFriendServiceServer) RejectFriendRequest(arg0 context.Context, arg1 *pb.UserIDsPair) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectFriendRequest", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectFriendRequest indicates an expected call of RejectFriendRequest.
func (mr *MockFriendServiceServerMockRecorder) RejectFriendRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectFriendRequest", reflect.TypeOf((*MockFriendServiceServer)(nil).RejectFriendRequest), arg0, arg1)
}

// RemoveFriend mocks base method.
func (m *MockFriendServiceServer) RemoveFriend(arg0 context.Context, arg1 *pb.UserIDsPair) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFriend", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFriend indicates an expected call of RemoveFriend.
func (mr *MockFriendServiceServerMockRecorder) RemoveFriend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriend", reflect.TypeOf((*MockFriendServiceServer)(nil).RemoveFriend), arg0, arg1)
}

// SearchShortProfilesByFullNameAndRelationType mocks base method.
func (m *MockFriendServiceServer) SearchShortProfilesByFullNameAndRelationType(arg0 context.Context, arg1 *pb.SearchProfilesRequest) (*pb.ShortProfileList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchShortProfilesByFullNameAndRelationType", arg0, arg1)
	ret0, _ := ret[0].(*pb.ShortProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchShortProfilesByFullNameAndRelationType indicates an expected call of SearchShortProfilesByFullNameAndRelationType.
func (mr *MockFriendServiceServerMockRecorder) SearchShortProfilesByFullNameAndRelationType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchShortProfilesByFullNameAndRelationType", reflect.TypeOf((*MockFriendServiceServer)(nil).SearchShortProfilesByFullNameAndRelationType), arg0, arg1)
}

// SendFriendRequest mocks base method.
func (m *MockFriendServiceServer) SendFriendRequest(arg0 context.Context, arg1 *pb.SendFriendRequestRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockFriendServiceServerMockRecorder) SendFriendRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockFriendServiceServer)(nil).SendFriendRequest), arg0, arg1)
}

// mustEmbedUnimplementedFriendServiceServer mocks base method.
func (m *MockFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFriendServiceServer")
}

// mustEmbedUnimplementedFriendServiceServer indicates an expected call of mustEmbedUnimplementedFriendServiceServer.
func (mr *MockFriendServiceServerMockRecorder) mustEmbedUnimplementedFriendServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFriendServiceServer", reflect.TypeOf((*MockFriendServiceServer)(nil).mustEmbedUnimplementedFriendServiceServer))
}

// MockUnsafeFriendServiceServer is a mock of UnsafeFriendServiceServer interface.
type MockUnsafeFriendServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeFriendServiceServerMockRecorder
}

// MockUnsafeFriendServiceServerMockRecorder is the mock recorder for MockUnsafeFriendServiceServer.
type MockUnsafeFriendServiceServerMockRecorder struct {
	mock *MockUnsafeFriendServiceServer
}

// NewMockUnsafeFriendServiceServer creates a new mock instance.
func NewMockUnsafeFriendServiceServer(ctrl *gomock.Controller) *MockUnsafeFriendServiceServer {
	mock := &MockUnsafeFriendServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeFriendServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeFriendServiceServer) EXPECT() *MockUnsafeFriendServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedFriendServiceServer mocks base method.
func (m *MockUnsafeFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFriendServiceServer")
}

// mustEmbedUnimplementedFriendServiceServer indicates an expected call of mustEmbedUnimplementedFriendServiceServer.
func (mr *MockUnsafeFriendServiceServerMockRecorder) mustEmbedUnimplementedFriendServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFriendServiceServer", reflect.TypeOf((*MockUnsafeFriendServiceServer)(nil).mustEmbedUnimplementedFriendServiceServer))
}
