// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: shared/pb/friend.proto

//    protoc --go_out=. --go-grpc_out=. shared/pb/friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIDsPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FriendID      int32                  `protobuf:"varint,2,opt,name=friendID,proto3" json:"friendID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDsPair) Reset() {
	*x = UserIDsPair{}
	mi := &file_shared_pb_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDsPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDsPair) ProtoMessage() {}

func (x *UserIDsPair) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDsPair.ProtoReflect.Descriptor instead.
func (*UserIDsPair) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{0}
}

func (x *UserIDsPair) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserIDsPair) GetFriendID() int32 {
	if x != nil {
		return x.FriendID
	}
	return 0
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionUserID  int32                  `protobuf:"varint,1,opt,name=actionUserID,proto3" json:"actionUserID,omitempty"`
	TargetUserID  int32                  `protobuf:"varint,2,opt,name=targetUserID,proto3" json:"targetUserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestRequest) GetActionUserID() int32 {
	if x != nil {
		return x.ActionUserID
	}
	return 0
}

func (x *SendFriendRequestRequest) GetTargetUserID() int32 {
	if x != nil {
		return x.TargetUserID
	}
	return 0
}

type GetFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequest) Reset() {
	*x = GetFriendsRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequest) ProtoMessage() {}

func (x *GetFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{2}
}

func (x *GetFriendsRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetFriendsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFriendsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllUsersRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetAllUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProfilesRequest) Reset() {
	*x = SearchProfilesRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProfilesRequest) ProtoMessage() {}

func (x *SearchProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProfilesRequest.ProtoReflect.Descriptor instead.
func (*SearchProfilesRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{4}
}

func (x *SearchProfilesRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SearchProfilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProfilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProfilesRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SearchProfilesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsRequest) Reset() {
	*x = GetFriendRequestsRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsRequest) ProtoMessage() {}

func (x *GetFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{5}
}

func (x *GetFriendRequestsRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetFriendRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFriendRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetSentRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSentRequestsRequest) Reset() {
	*x = GetSentRequestsRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSentRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSentRequestsRequest) ProtoMessage() {}

func (x *GetSentRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSentRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetSentRequestsRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{6}
}

func (x *GetSentRequestsRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetSentRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSentRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetFriendshipStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FriendID      int32                  `protobuf:"varint,2,opt,name=friendID,proto3" json:"friendID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendshipStatusRequest) Reset() {
	*x = GetFriendshipStatusRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipStatusRequest) ProtoMessage() {}

func (x *GetFriendshipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFriendshipStatusRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{7}
}

func (x *GetFriendshipStatusRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetFriendshipStatusRequest) GetFriendID() int32 {
	if x != nil {
		return x.FriendID
	}
	return 0
}

type CountUserRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountUserRelationsRequest) Reset() {
	*x = CountUserRelationsRequest{}
	mi := &file_shared_pb_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountUserRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUserRelationsRequest) ProtoMessage() {}

func (x *CountUserRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUserRelationsRequest.ProtoReflect.Descriptor instead.
func (*CountUserRelationsRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{8}
}

func (x *CountUserRelationsRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ShortProfileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ShortProfile        `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortProfileList) Reset() {
	*x = ShortProfileList{}
	mi := &file_shared_pb_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortProfileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortProfileList) ProtoMessage() {}

func (x *ShortProfileList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortProfileList.ProtoReflect.Descriptor instead.
func (*ShortProfileList) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{9}
}

func (x *ShortProfileList) GetProfiles() []*ShortProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type FriendshipStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendshipStatusResponse) Reset() {
	*x = FriendshipStatusResponse{}
	mi := &file_shared_pb_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendshipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipStatusResponse) ProtoMessage() {}

func (x *FriendshipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipStatusResponse.ProtoReflect.Descriptor instead.
func (*FriendshipStatusResponse) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{10}
}

func (x *FriendshipStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserRelationsCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Pending       int32                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Sent          int32                  `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Blocked       int32                  `protobuf:"varint,4,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsCountsResponse) Reset() {
	*x = UserRelationsCountsResponse{}
	mi := &file_shared_pb_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsCountsResponse) ProtoMessage() {}

func (x *UserRelationsCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsCountsResponse.ProtoReflect.Descriptor instead.
func (*UserRelationsCountsResponse) Descriptor() ([]byte, []int) {
	return file_shared_pb_friend_proto_rawDescGZIP(), []int{11}
}

func (x *UserRelationsCountsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *UserRelationsCountsResponse) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *UserRelationsCountsResponse) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *UserRelationsCountsResponse) GetBlocked() int32 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

var File_shared_pb_friend_proto protoreflect.FileDescriptor

const file_shared_pb_friend_proto_rawDesc = "" +
	"\n" +
	"\x16shared/pb/friend.proto\x12\afriends\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17shared/pb/profile.proto\"A\n" +
	"\vUserIDsPair\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1a\n" +
	"\bfriendID\x18\x02 \x01(\x05R\bfriendID\"b\n" +
	"\x18SendFriendRequestRequest\x12\"\n" +
	"\factionUserID\x18\x01 \x01(\x05R\factionUserID\x12\"\n" +
	"\ftargetUserID\x18\x02 \x01(\x05R\ftargetUserID\"U\n" +
	"\x11GetFriendsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"V\n" +
	"\x12GetAllUsersRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\x89\x01\n" +
	"\x15SearchProfilesRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bfullName\x18\x04 \x01(\tR\bfullName\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\\\n" +
	"\x18GetFriendRequestsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"Z\n" +
	"\x16GetSentRequestsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"P\n" +
	"\x1aGetFriendshipStatusRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1a\n" +
	"\bfriendID\x18\x02 \x01(\x05R\bfriendID\"3\n" +
	"\x19CountUserRelationsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\"E\n" +
	"\x10ShortProfileList\x121\n" +
	"\bprofiles\x18\x01 \x03(\v2\x15.profile.ShortProfileR\bprofiles\"2\n" +
	"\x18FriendshipStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x81\x01\n" +
	"\x1bUserRelationsCountsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x18\n" +
	"\apending\x18\x02 \x01(\x05R\apending\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\x05R\x04sent\x12\x18\n" +
	"\ablocked\x18\x04 \x01(\x05R\ablocked2\xff\x06\n" +
	"\rFriendService\x12N\n" +
	"\x11SendFriendRequest\x12!.friends.SendFriendRequestRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x13AcceptFriendRequest\x12\x14.friends.UserIDsPair\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x13RejectFriendRequest\x12\x14.friends.UserIDsPair\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\fRemoveFriend\x12\x14.friends.UserIDsPair\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"GetFriends\x12\x1a.friends.GetFriendsRequest\x1a\x19.friends.ShortProfileList\x12E\n" +
	"\vGetAllUsers\x12\x1b.friends.GetAllUsersRequest\x1a\x19.friends.ShortProfileList\x12i\n" +
	",SearchShortProfilesByFullNameAndRelationType\x12\x1e.friends.SearchProfilesRequest\x1a\x19.friends.ShortProfileList\x12Q\n" +
	"\x11GetFriendRequests\x12!.friends.GetFriendRequestsRequest\x1a\x19.friends.ShortProfileList\x12M\n" +
	"\x0fGetSentRequests\x12\x1f.friends.GetSentRequestsRequest\x1a\x19.friends.ShortProfileList\x12]\n" +
	"\x13GetFriendshipStatus\x12#.friends.GetFriendshipStatusRequest\x1a!.friends.FriendshipStatusResponse\x12^\n" +
	"\x12CountUserRelations\x12\".friends.CountUserRelationsRequest\x1a$.friends.UserRelationsCountsResponseB\x0fZ\r/shared/pb;pbb\x06proto3"

var (
	file_shared_pb_friend_proto_rawDescOnce sync.Once
	file_shared_pb_friend_proto_rawDescData []byte
)

func file_shared_pb_friend_proto_rawDescGZIP() []byte {
	file_shared_pb_friend_proto_rawDescOnce.Do(func() {
		file_shared_pb_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_pb_friend_proto_rawDesc), len(file_shared_pb_friend_proto_rawDesc)))
	})
	return file_shared_pb_friend_proto_rawDescData
}

var file_shared_pb_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_shared_pb_friend_proto_goTypes = []any{
	(*UserIDsPair)(nil),                 // 0: friends.UserIDsPair
	(*SendFriendRequestRequest)(nil),    // 1: friends.SendFriendRequestRequest
	(*GetFriendsRequest)(nil),           // 2: friends.GetFriendsRequest
	(*GetAllUsersRequest)(nil),          // 3: friends.GetAllUsersRequest
	(*SearchProfilesRequest)(nil),       // 4: friends.SearchProfilesRequest
	(*GetFriendRequestsRequest)(nil),    // 5: friends.GetFriendRequestsRequest
	(*GetSentRequestsRequest)(nil),      // 6: friends.GetSentRequestsRequest
	(*GetFriendshipStatusRequest)(nil),  // 7: friends.GetFriendshipStatusRequest
	(*CountUserRelationsRequest)(nil),   // 8: friends.CountUserRelationsRequest
	(*ShortProfileList)(nil),            // 9: friends.ShortProfileList
	(*FriendshipStatusResponse)(nil),    // 10: friends.FriendshipStatusResponse
	(*UserRelationsCountsResponse)(nil), // 11: friends.UserRelationsCountsResponse
	(*ShortProfile)(nil),                // 12: profile.ShortProfile
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
}
var file_shared_pb_friend_proto_depIdxs = []int32{
	12, // 0: friends.ShortProfileList.profiles:type_name -> profile.ShortProfile
	1,  // 1: friends.FriendService.SendFriendRequest:input_type -> friends.SendFriendRequestRequest
	0,  // 2: friends.FriendService.AcceptFriendRequest:input_type -> friends.UserIDsPair
	0,  // 3: friends.FriendService.RejectFriendRequest:input_type -> friends.UserIDsPair
	0,  // 4: friends.FriendService.RemoveFriend:input_type -> friends.UserIDsPair
	2,  // 5: friends.FriendService.GetFriends:input_type -> friends.GetFriendsRequest
	3,  // 6: friends.FriendService.GetAllUsers:input_type -> friends.GetAllUsersRequest
	4,  // 7: friends.FriendService.SearchShortProfilesByFullNameAndRelationType:input_type -> friends.SearchProfilesRequest
	5,  // 8: friends.FriendService.GetFriendRequests:input_type -> friends.GetFriendRequestsRequest
	6,  // 9: friends.FriendService.GetSentRequests:input_type -> friends.GetSentRequestsRequest
	7,  // 10: friends.FriendService.GetFriendshipStatus:input_type -> friends.GetFriendshipStatusRequest
	8,  // 11: friends.FriendService.CountUserRelations:input_type -> friends.CountUserRelationsRequest
	13, // 12: friends.FriendService.SendFriendRequest:output_type -> google.protobuf.Empty
	13, // 13: friends.FriendService.AcceptFriendRequest:output_type -> google.protobuf.Empty
	13, // 14: friends.FriendService.RejectFriendRequest:output_type -> google.protobuf.Empty
	13, // 15: friends.FriendService.RemoveFriend:output_type -> google.protobuf.Empty
	9,  // 16: friends.FriendService.GetFriends:output_type -> friends.ShortProfileList
	9,  // 17: friends.FriendService.GetAllUsers:output_type -> friends.ShortProfileList
	9,  // 18: friends.FriendService.SearchShortProfilesByFullNameAndRelationType:output_type -> friends.ShortProfileList
	9,  // 19: friends.FriendService.GetFriendRequests:output_type -> friends.ShortProfileList
	9,  // 20: friends.FriendService.GetSentRequests:output_type -> friends.ShortProfileList
	10, // 21: friends.FriendService.GetFriendshipStatus:output_type -> friends.FriendshipStatusResponse
	11, // 22: friends.FriendService.CountUserRelations:output_type -> friends.UserRelationsCountsResponse
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_shared_pb_friend_proto_init() }
func file_shared_pb_friend_proto_init() {
	if File_shared_pb_friend_proto != nil {
		return
	}
	file_shared_pb_profile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_pb_friend_proto_rawDesc), len(file_shared_pb_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_pb_friend_proto_goTypes,
		DependencyIndexes: file_shared_pb_friend_proto_depIdxs,
		MessageInfos:      file_shared_pb_friend_proto_msgTypes,
	}.Build()
	File_shared_pb_friend_proto = out.File
	file_shared_pb_friend_proto_goTypes = nil
	file_shared_pb_friend_proto_depIdxs = nil
}
