// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: shared/pb/friend.proto

//    protoc --go_out=. --go-grpc_out=. shared/pb/friend.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendService_SendFriendRequest_FullMethodName                            = "/friends.FriendService/SendFriendRequest"
	FriendService_AcceptFriendRequest_FullMethodName                          = "/friends.FriendService/AcceptFriendRequest"
	FriendService_RejectFriendRequest_FullMethodName                          = "/friends.FriendService/RejectFriendRequest"
	FriendService_RemoveFriend_FullMethodName                                 = "/friends.FriendService/RemoveFriend"
	FriendService_GetFriends_FullMethodName                                   = "/friends.FriendService/GetFriends"
	FriendService_GetAllUsers_FullMethodName                                  = "/friends.FriendService/GetAllUsers"
	FriendService_SearchShortProfilesByFullNameAndRelationType_FullMethodName = "/friends.FriendService/SearchShortProfilesByFullNameAndRelationType"
	FriendService_GetFriendRequests_FullMethodName                            = "/friends.FriendService/GetFriendRequests"
	FriendService_GetSentRequests_FullMethodName                              = "/friends.FriendService/GetSentRequests"
	FriendService_GetFriendshipStatus_FullMethodName                          = "/friends.FriendService/GetFriendshipStatus"
	FriendService_CountUserRelations_FullMethodName                           = "/friends.FriendService/CountUserRelations"
)

// FriendServiceClient is the client API for FriendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendServiceClient interface {
	SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AcceptFriendRequest(ctx context.Context, in *UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RejectFriendRequest(ctx context.Context, in *UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveFriend(ctx context.Context, in *UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*ShortProfileList, error)
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*ShortProfileList, error)
	SearchShortProfilesByFullNameAndRelationType(ctx context.Context, in *SearchProfilesRequest, opts ...grpc.CallOption) (*ShortProfileList, error)
	GetFriendRequests(ctx context.Context, in *GetFriendRequestsRequest, opts ...grpc.CallOption) (*ShortProfileList, error)
	GetSentRequests(ctx context.Context, in *GetSentRequestsRequest, opts ...grpc.CallOption) (*ShortProfileList, error)
	GetFriendshipStatus(ctx context.Context, in *GetFriendshipStatusRequest, opts ...grpc.CallOption) (*FriendshipStatusResponse, error)
	CountUserRelations(ctx context.Context, in *CountUserRelationsRequest, opts ...grpc.CallOption) (*UserRelationsCountsResponse, error)
}

type friendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendServiceClient(cc grpc.ClientConnInterface) FriendServiceClient {
	return &friendServiceClient{cc}
}

func (c *friendServiceClient) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendService_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) AcceptFriendRequest(ctx context.Context, in *UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendService_AcceptFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) RejectFriendRequest(ctx context.Context, in *UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendService_RejectFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) RemoveFriend(ctx context.Context, in *UserIDsPair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendService_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*ShortProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortProfileList)
	err := c.cc.Invoke(ctx, FriendService_GetFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*ShortProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortProfileList)
	err := c.cc.Invoke(ctx, FriendService_GetAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SearchShortProfilesByFullNameAndRelationType(ctx context.Context, in *SearchProfilesRequest, opts ...grpc.CallOption) (*ShortProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortProfileList)
	err := c.cc.Invoke(ctx, FriendService_SearchShortProfilesByFullNameAndRelationType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetFriendRequests(ctx context.Context, in *GetFriendRequestsRequest, opts ...grpc.CallOption) (*ShortProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortProfileList)
	err := c.cc.Invoke(ctx, FriendService_GetFriendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetSentRequests(ctx context.Context, in *GetSentRequestsRequest, opts ...grpc.CallOption) (*ShortProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortProfileList)
	err := c.cc.Invoke(ctx, FriendService_GetSentRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetFriendshipStatus(ctx context.Context, in *GetFriendshipStatusRequest, opts ...grpc.CallOption) (*FriendshipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendshipStatusResponse)
	err := c.cc.Invoke(ctx, FriendService_GetFriendshipStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CountUserRelations(ctx context.Context, in *CountUserRelationsRequest, opts ...grpc.CallOption) (*UserRelationsCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRelationsCountsResponse)
	err := c.cc.Invoke(ctx, FriendService_CountUserRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServiceServer is the server API for FriendService service.
// All implementations must embed UnimplementedFriendServiceServer
// for forward compatibility.
type FriendServiceServer interface {
	SendFriendRequest(context.Context, *SendFriendRequestRequest) (*emptypb.Empty, error)
	AcceptFriendRequest(context.Context, *UserIDsPair) (*emptypb.Empty, error)
	RejectFriendRequest(context.Context, *UserIDsPair) (*emptypb.Empty, error)
	RemoveFriend(context.Context, *UserIDsPair) (*emptypb.Empty, error)
	GetFriends(context.Context, *GetFriendsRequest) (*ShortProfileList, error)
	GetAllUsers(context.Context, *GetAllUsersRequest) (*ShortProfileList, error)
	SearchShortProfilesByFullNameAndRelationType(context.Context, *SearchProfilesRequest) (*ShortProfileList, error)
	GetFriendRequests(context.Context, *GetFriendRequestsRequest) (*ShortProfileList, error)
	GetSentRequests(context.Context, *GetSentRequestsRequest) (*ShortProfileList, error)
	GetFriendshipStatus(context.Context, *GetFriendshipStatusRequest) (*FriendshipStatusResponse, error)
	CountUserRelations(context.Context, *CountUserRelationsRequest) (*UserRelationsCountsResponse, error)
	mustEmbedUnimplementedFriendServiceServer()
}

// UnimplementedFriendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendServiceServer struct{}

func (UnimplementedFriendServiceServer) SendFriendRequest(context.Context, *SendFriendRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedFriendServiceServer) AcceptFriendRequest(context.Context, *UserIDsPair) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (UnimplementedFriendServiceServer) RejectFriendRequest(context.Context, *UserIDsPair) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectFriendRequest not implemented")
}
func (UnimplementedFriendServiceServer) RemoveFriend(context.Context, *UserIDsPair) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedFriendServiceServer) GetFriends(context.Context, *GetFriendsRequest) (*ShortProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriends not implemented")
}
func (UnimplementedFriendServiceServer) GetAllUsers(context.Context, *GetAllUsersRequest) (*ShortProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedFriendServiceServer) SearchShortProfilesByFullNameAndRelationType(context.Context, *SearchProfilesRequest) (*ShortProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchShortProfilesByFullNameAndRelationType not implemented")
}
func (UnimplementedFriendServiceServer) GetFriendRequests(context.Context, *GetFriendRequestsRequest) (*ShortProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendRequests not implemented")
}
func (UnimplementedFriendServiceServer) GetSentRequests(context.Context, *GetSentRequestsRequest) (*ShortProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSentRequests not implemented")
}
func (UnimplementedFriendServiceServer) GetFriendshipStatus(context.Context, *GetFriendshipStatusRequest) (*FriendshipStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendshipStatus not implemented")
}
func (UnimplementedFriendServiceServer) CountUserRelations(context.Context, *CountUserRelationsRequest) (*UserRelationsCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountUserRelations not implemented")
}
func (UnimplementedFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {}
func (UnimplementedFriendServiceServer) testEmbeddedByValue()                       {}

// UnsafeFriendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServiceServer will
// result in compilation errors.
type UnsafeFriendServiceServer interface {
	mustEmbedUnimplementedFriendServiceServer()
}

func RegisterFriendServiceServer(s grpc.ServiceRegistrar, srv FriendServiceServer) {
	// If the following call pancis, it indicates UnimplementedFriendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendService_ServiceDesc, srv)
}

func _FriendService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SendFriendRequest(ctx, req.(*SendFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDsPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_AcceptFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).AcceptFriendRequest(ctx, req.(*UserIDsPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_RejectFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDsPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).RejectFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_RejectFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).RejectFriendRequest(ctx, req.(*UserIDsPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDsPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).RemoveFriend(ctx, req.(*UserIDsPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetFriends(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SearchShortProfilesByFullNameAndRelationType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SearchShortProfilesByFullNameAndRelationType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SearchShortProfilesByFullNameAndRelationType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SearchShortProfilesByFullNameAndRelationType(ctx, req.(*SearchProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetFriendRequests(ctx, req.(*GetFriendRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetSentRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSentRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetSentRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetSentRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetSentRequests(ctx, req.(*GetSentRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetFriendshipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendshipStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetFriendshipStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetFriendshipStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetFriendshipStatus(ctx, req.(*GetFriendshipStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CountUserRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountUserRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CountUserRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CountUserRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CountUserRelations(ctx, req.(*CountUserRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendService_ServiceDesc is the grpc.ServiceDesc for FriendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friends.FriendService",
	HandlerType: (*FriendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFriendRequest",
			Handler:    _FriendService_SendFriendRequest_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _FriendService_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "RejectFriendRequest",
			Handler:    _FriendService_RejectFriendRequest_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _FriendService_RemoveFriend_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _FriendService_GetFriends_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _FriendService_GetAllUsers_Handler,
		},
		{
			MethodName: "SearchShortProfilesByFullNameAndRelationType",
			Handler:    _FriendService_SearchShortProfilesByFullNameAndRelationType_Handler,
		},
		{
			MethodName: "GetFriendRequests",
			Handler:    _FriendService_GetFriendRequests_Handler,
		},
		{
			MethodName: "GetSentRequests",
			Handler:    _FriendService_GetSentRequests_Handler,
		},
		{
			MethodName: "GetFriendshipStatus",
			Handler:    _FriendService_GetFriendshipStatus_Handler,
		},
		{
			MethodName: "CountUserRelations",
			Handler:    _FriendService_CountUserRelations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/pb/friend.proto",
}
