events {}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    client_max_body_size 100M;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}
