
server {
    listen 80;
    server_name unitesm.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name unitesm.ru;

    ssl_certificate     /etc/nginx/certs/live/unitesm.ru-0001/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/unitesm.ru-0001/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    root /usr/share/nginx/html;

    # Кэширование статических файлов
    location ~* \.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpeg|avi|zip|gz|bz2|rar|swf|webp)$ {
        expires 30d; # Кэшировать файлы на стороне клиента (браузера) на 30 дней
        add_header Cache-Control "public"; # Установка заголовка Cache-Control
        # Отключение логирования доступа для статики (опционально)
        access_log off;
    }

    # Основная логика обработки запросов
    location / {
        try_files $uri $uri/ =404;
    }


    location /api/ {
        proxy_pass http://main:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ws {
        proxy_pass http://main:8080/api/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

