// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/isloggedin": {
            "get": {
                "description": "Возвращает ID пользователя, если сессия валидна",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверить авторизацию пользователя",
                "responses": {
                    "200": {
                        "description": "Пользователь авторизован",
                        "schema": {
                            "$ref": "#/definitions/handler.IsLoggedInResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Логин с email и паролем, возвращает cookie сессии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Удаляет cookie сессии, разлогинивает пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создает нового пользователя с профилем и устанавливает сессию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "registerRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/chats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает постраничный список чатов для аутентифицированного пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Получение чатов пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of chats to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of chats",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.FullChat"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/chats/user/{id}": {
            "get": {
                "description": "Возвращает ID чата между текущим пользователем и указанным userID, создавая чат при отсутствии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Получить или создать чат с пользователем",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ChatIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/chats/{chatID}/message": {
            "post": {
                "description": "Создает новое сообщение в указанном чате",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Создать сообщение",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID чата",
                        "name": "chatID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Тело сообщения",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Message"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/chats/{id}/messages": {
            "get": {
                "description": "Возвращает сообщения из чата с пагинацией и краткую информацию об авторах",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Получить сообщения чата с авторами",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID чата",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Лимит количества сообщений",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение для пагинации",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.MessagesWithAuthors"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список друзей пользователя с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Получить список друзей",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Количество друзей на странице",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ со списком друзей",
                        "schema": {
                            "$ref": "#/definitions/handler.FriendsResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры пагинации",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends/requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список входящих запросов на дружбу с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Получить входящие запросы в друзья",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Количество запросов на странице",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ со списком запросов",
                        "schema": {
                            "$ref": "#/definitions/handler.FriendRequestsResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры пагинации",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends/sent": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список отправленных запросов на дружбу с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Получить отправленные запросы в друзья",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Количество запросов на странице",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ со списком отправленных запросов",
                        "schema": {
                            "$ref": "#/definitions/handler.FriendRequestsResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры пагинации",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Отправляет запрос на дружбу другому пользователю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Отправить запрос в друзья",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя, которому отправляется запрос",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос успешно отправлен",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID пользователя или попытка добавить самого себя",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "409": {
                        "description": "Запрос уже существует или пользователи уже друзья",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет пользователя из списка друзей",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Удалить из друзей",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно удален из друзей",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователи не являются друзьями",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends/{id}/accept": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Принимает входящий запрос на дружбу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Принять запрос в друзья",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя (отправителя запроса)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос успешно принят",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Запрос не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends/{id}/reject": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Отклоняет входящий запрос на дружбу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Отклонить запрос в друзья",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя (отправителя запроса)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос успешно отклонен",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Запрос не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/friends/{id}/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает текущий статус дружбы с указанным пользователем",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Получить статус дружбы",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ со статусом дружбы",
                        "schema": {
                            "$ref": "#/definitions/handler.FriendshipStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "Возвращает список постов с поддержкой пагинации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получить посты с пагинацией",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Количество постов на странице",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с постами",
                        "schema": {
                            "$ref": "#/definitions/handler.PostsResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создает новый пост от имени текущего пользователя с возможностью загрузки файлов",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Создать новый пост",
                "parameters": [
                    {
                        "maxLength": 4096,
                        "minLength": 24,
                        "type": "string",
                        "description": "Текст поста (24-4096 символов)",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "Вложения к посту",
                        "name": "attachments",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "Фотографии к посту",
                        "name": "photos",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пост успешно создан",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "Возвращает пост по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получить пост по ID",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пост найден",
                        "schema": {
                            "$ref": "#/definitions/domain.Post"
                        }
                    },
                    "400": {
                        "description": "Неверный ID поста",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Пост не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет существующий пост (только автор) с возможностью замены файлов",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Обновить пост",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maxLength": 4096,
                        "minLength": 24,
                        "type": "string",
                        "description": "Текст поста (24-4096 символов)",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "Вложения к посту",
                        "name": "attachments",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "Фотографии к посту",
                        "name": "photos",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пост успешно обновлен",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не автор поста)",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Пост не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет пост (только автор)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Удалить пост",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пост успешно удален",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный ID поста",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не автор поста)",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Пост не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет данные пользователя и загружает новый аватар, если он передан.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновление профиля",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JSON с данными профиля",
                        "name": "profile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Новый аватар пользователя",
                        "name": "avatar",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data / missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/profile/avatar": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Загружает новый аватар пользователя.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновление аватара",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Новый аватар пользователя",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avatar updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing avatar field",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/profile/header": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Загружает новый header пользователя.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновление header",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Новый header пользователя",
                        "name": "header",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Header updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing header field",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/profile/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает профиль пользователя по его ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получение профиля по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Профиль пользователя",
                        "schema": {
                            "$ref": "#/definitions/domain.Profile"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID / User does not exist",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userID}/posts": {
            "get": {
                "description": "Возвращает посты конкретного пользователя с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получить посты пользователя",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Количество постов на странице",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с постами пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.PostsResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Устанавливает WebSocket соединение для текущего пользователя и регистрирует его в WSHub",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WS"
                ],
                "summary": "Подключение к WebSocket",
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "400": {
                        "description": "Неверный запрос или отсутствует userID в контексте",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при апгрейде соединения",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.FriendshipStatus": {
            "type": "string",
            "enum": [
                "pending",
                "accepted",
                "rejected",
                "blocked"
            ],
            "x-enum-varnames": [
                "FriendshipPending",
                "FriendshipAccepted",
                "FriendshipRejected",
                "FriendshipBlocked"
            ]
        },
        "domain.FriendshipWithProfile": {
            "type": "object",
            "properties": {
                "actionUserID": {
                    "description": "Кто отправил запрос",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "firstUserID": {
                    "type": "integer"
                },
                "friend": {
                    "$ref": "#/definitions/domain.ShortProfile"
                },
                "id": {
                    "type": "integer"
                },
                "secondUserID": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/domain.FriendshipStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.FullChat": {
            "type": "object",
            "properties": {
                "avatarPath": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isGroup": {
                    "type": "boolean"
                },
                "lastMessage": {
                    "$ref": "#/definitions/domain.Message"
                },
                "lastMessageAuthor": {
                    "$ref": "#/definitions/domain.ShortProfile"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Message": {
            "type": "object",
            "properties": {
                "authorID": {
                    "type": "integer"
                },
                "chatID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "domain.MessagesWithAuthors": {
            "type": "object",
            "properties": {
                "authors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.ShortProfile"
                    }
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Message"
                    }
                }
            }
        },
        "domain.Post": {
            "type": "object",
            "properties": {
                "attachments": {
                    "description": "в БД табличка post_attachments называется",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorID": {
                    "description": "в БД табличка posts называется",
                    "type": "integer"
                },
                "created_at": {
                    "description": "в БД табличка posts называется",
                    "type": "string"
                },
                "id": {
                    "description": "в БД табличка posts называется",
                    "type": "integer"
                },
                "photos": {
                    "description": "в БД табличка post_photos называется",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "text": {
                    "description": "в БД табличка posts называется",
                    "type": "string"
                },
                "updated_at": {
                    "description": "в БД табличка posts называется",
                    "type": "string"
                }
            }
        },
        "domain.Profile": {
            "type": "object",
            "properties": {
                "aboutMyself": {
                    "type": "string"
                },
                "avatarPath": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "headerPath": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "domain.RegisterRequest": {
            "type": "object",
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "example": "123123"
                },
                "dob": {
                    "type": "string",
                    "example": "1990-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.ru"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "123123"
                }
            }
        },
        "domain.ShortProfile": {
            "type": "object",
            "properties": {
                "avatarPath": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.ChatIDResponse": {
            "type": "object",
            "properties": {
                "chatID": {
                    "type": "integer"
                }
            }
        },
        "handler.FriendRequestsResponse": {
            "description": "Ответ с пагинированным списком запросов в друзья",
            "type": "object",
            "properties": {
                "hasNext": {
                    "description": "Есть ли следующая страница",
                    "type": "boolean",
                    "example": true
                },
                "page": {
                    "description": "Текущая страница",
                    "type": "integer",
                    "example": 1
                },
                "requests": {
                    "description": "Список запросов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FriendshipWithProfile"
                    }
                },
                "totalPages": {
                    "description": "Общее количество страниц",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handler.FriendsResponse": {
            "description": "Ответ с пагинированным списком друзей",
            "type": "object",
            "properties": {
                "friends": {
                    "description": "Список друзей",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ShortProfile"
                    }
                },
                "hasNext": {
                    "description": "Есть ли следующая страница",
                    "type": "boolean",
                    "example": true
                },
                "page": {
                    "description": "Текущая страница",
                    "type": "integer",
                    "example": 1
                },
                "totalPages": {
                    "description": "Общее количество страниц",
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "handler.FriendshipStatusResponse": {
            "description": "Ответ с текущим статусом дружбы между пользователями",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Статус дружбы",
                    "enum": [
                        "pending",
                        "accepted",
                        "rejected",
                        "blocked"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.FriendshipStatus"
                        }
                    ],
                    "example": "pending"
                }
            }
        },
        "handler.IsLoggedInResponse": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "integer"
                }
            }
        },
        "handler.JSONResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.MessageIDResponse": {
            "type": "object",
            "properties": {
                "messageID": {
                    "type": "integer"
                }
            }
        },
        "handler.PostsResponse": {
            "description": "Ответ с пагинированным списком постов",
            "type": "object",
            "properties": {
                "hasNext": {
                    "description": "Есть ли следующая страница",
                    "type": "boolean",
                    "example": true
                },
                "page": {
                    "description": "Текущая страница",
                    "type": "integer",
                    "example": 1
                },
                "posts": {
                    "description": "Список постов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Post"
                    }
                },
                "totalPages": {
                    "description": "Общее количество страниц",
                    "type": "integer",
                    "example": 5
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "VK API",
	Description:      "This is a VK API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
