basePath: /api/
definitions:
  domain.FullChat:
    properties:
      avatarPath:
        type: string
      id:
        type: integer
      isGroup:
        type: boolean
      lastMessage:
        $ref: '#/definitions/domain.Message'
      lastMessageAuthor:
        $ref: '#/definitions/domain.ShortProfile'
      name:
        type: string
    type: object
  domain.Message:
    properties:
      authorID:
        type: integer
      chatID:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      text:
        type: string
    type: object
  domain.Post:
    properties:
      attachments:
        description: в БД табличка post_attachments называется
        items:
          type: string
        type: array
      authorID:
        description: в БД табличка posts называется
        type: integer
      created_at:
        description: в БД табличка posts называется
        type: string
      id:
        description: в БД табличка posts называется
        type: integer
      photos:
        description: в БД табличка post_photos называется
        items:
          type: string
        type: array
      text:
        description: в БД табличка posts называется
        type: string
      updated_at:
        description: в БД табличка posts называется
        type: string
    type: object
  domain.Profile:
    properties:
      aboutMyself:
        type: string
      avatarPath:
        type: string
      dob:
        type: string
      firstName:
        type: string
      gender:
        type: string
      headerPath:
        type: string
      lastName:
        type: string
      userID:
        type: integer
    type: object
  domain.ShortProfile:
    properties:
      avatarPath:
        type: string
      fullName:
        type: string
      userID:
        type: integer
    type: object
  handler.ChatIDResponse:
    properties:
      chatID:
        type: integer
    type: object
  handler.CreatePostRequest:
    properties:
      attachments:
        items:
          type: string
        type: array
      photos:
        items:
          type: string
        type: array
      text:
        type: string
    type: object
  handler.IsLoggedInResponse:
    properties:
      userID:
        type: integer
    type: object
  handler.JSONResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  handler.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.MessageIDResponse:
    properties:
      messageID:
        type: integer
    type: object
  handler.MessagesWithAuthorsResp:
    properties:
      authors:
        items:
          $ref: '#/definitions/domain.ShortProfile'
        type: array
      messages:
        items:
          $ref: '#/definitions/domain.Message'
        type: array
    type: object
  handler.PostsResponse:
    properties:
      hasNext:
        type: boolean
      page:
        type: integer
      posts:
        items:
          $ref: '#/definitions/domain.Post'
        type: array
      totalPages:
        type: integer
    type: object
  handler.RegisterRequest:
    properties:
      confirmPassword:
        example: "123123"
        type: string
      dob:
        example: "1990-01-01T00:00:00Z"
        type: string
      email:
        example: example@example.ru
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastName:
        type: string
      password:
        example: "123123"
        type: string
    type: object
  handler.UpdatePostRequest:
    properties:
      attachments:
        items:
          type: string
        type: array
      photos:
        items:
          type: string
        type: array
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a VK API.
  termsOfService: http://swagger.io/terms/
  title: VK API
  version: "1.0"
paths:
  /auth/isloggedin:
    get:
      description: Возвращает ID пользователя, если сессия валидна
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь авторизован
          schema:
            $ref: '#/definitions/handler.IsLoggedInResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Проверить авторизацию пользователя
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Логин с email и паролем, возвращает cookie сессии
      parameters:
      - description: Данные для входа
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /auth/logout:
    post:
      description: Удаляет cookie сессии, разлогинивает пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Выход пользователя
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя с профилем и устанавливает сессию
      parameters:
      - description: Данные для регистрации
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /chats:
    get:
      consumes:
      - application/json
      description: Возвращает постраничный список чатов для аутентифицированного пользователя.
      parameters:
      - default: 20
        description: Number of chats to return
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of chats
          schema:
            items:
              $ref: '#/definitions/domain.FullChat'
            type: array
        "400":
          description: Invalid query parameters
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      security:
      - ApiKeyAuth: []
      summary: Получение чатов пользователя
      tags:
      - chats
  /chats/{chatID}/message:
    post:
      consumes:
      - application/json
      description: Создает новое сообщение в указанном чате
      parameters:
      - description: ID чата
        in: path
        name: chatID
        required: true
        type: integer
      - description: Тело сообщения
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/domain.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.MessageIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Создать сообщение
      tags:
      - messages
  /chats/{id}/messages:
    get:
      description: Возвращает сообщения из чата с пагинацией и краткую информацию
        об авторах
      parameters:
      - description: ID чата
        in: path
        name: id
        required: true
        type: integer
      - default: 20
        description: Лимит количества сообщений
        in: query
        name: limit
        type: integer
      - default: 0
        description: Смещение для пагинации
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.MessagesWithAuthorsResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Получить сообщения чата с авторами
      tags:
      - messages
  /chats/user/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает ID чата между текущим пользователем и указанным userID,
        создавая чат при отсутствии
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ChatIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Получить или создать чат с пользователем
      tags:
      - chats
  /posts:
    post:
      consumes:
      - application/json
      description: Создает новый пост от имени текущего пользователя
      parameters:
      - description: Данные поста
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/handler.CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      security:
      - ApiKeyAuth: []
      summary: Создать новый пост
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет пост (только автор)
      parameters:
      - description: ID поста
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      security:
      - ApiKeyAuth: []
      summary: Удалить пост
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: Возвращает пост по его идентификатору
      parameters:
      - description: ID поста
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Получить пост по ID
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Обновляет существующий пост (только автор)
      parameters:
      - description: ID поста
        in: path
        name: id
        required: true
        type: integer
      - description: Обновленные данные поста
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/handler.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      security:
      - ApiKeyAuth: []
      summary: Обновить пост
      tags:
      - posts
  /profile:
    put:
      consumes:
      - multipart/form-data
      description: Обновляет данные пользователя и загружает новый аватар, если он
        передан.
      parameters:
      - description: JSON с данными профиля
        in: formData
        name: profile
        required: true
        type: string
      - description: Новый аватар пользователя
        in: formData
        name: avatar
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Profile updated
          schema:
            type: string
        "400":
          description: Invalid data / missing fields
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Обновление профиля
      tags:
      - profile
  /profile/{id}:
    get:
      description: Возвращает профиль пользователя по его ID.
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Профиль пользователя
          schema:
            $ref: '#/definitions/domain.Profile'
        "400":
          description: Invalid user ID / User does not exist
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Получение профиля по ID
      tags:
      - profile
  /profile/avatar:
    put:
      consumes:
      - multipart/form-data
      description: Загружает новый аватар пользователя.
      parameters:
      - description: Новый аватар пользователя
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Avatar updated
          schema:
            type: string
        "400":
          description: Missing avatar field
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Обновление аватара
      tags:
      - profile
  /profile/header:
    put:
      consumes:
      - multipart/form-data
      description: Загружает новый header пользователя.
      parameters:
      - description: Новый header пользователя
        in: formData
        name: header
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Header updated
          schema:
            type: string
        "400":
          description: Missing header field
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Обновление header
      tags:
      - profile
  /users/{userID}/posts:
    get:
      consumes:
      - application/json
      description: Возвращает посты конкретного пользователя с пагинацией
      parameters:
      - description: ID пользователя
        in: path
        name: userID
        required: true
        type: integer
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 20
        description: Количество постов на странице
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PostsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Получить посты пользователя
      tags:
      - posts
swagger: "2.0"
