name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v2.3
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v -race ./...

